project:
  type: website
  output-dir: docs

website:
  title: "Evaluación de Programas 2023"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/rojasirvin/quarto-course-website-template
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: programa.qmd
        text: Programas
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

