project:
  type: website
  output-dir: docs

website:
  title: "Evaluación de Programas 2023"
  sidebar:
    background: primary
    logo: "iconoEvaluaciondeProgramasSociales.jpg"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/rojasirvin/quarto-course-website-template
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: programa.qmd
        text: Programa
      - href: reglas.qmd
        text: Reglas
      - href: lecturas.qmd
        text: Lecturas
      - href: presentaciones.qmd
        text: Presentaciones
      - href: tareas.qmd
        text: Tareas
      - href: materiales.qmd
        text: Materiales
      - href: schedule.qmd
        text: Schedule


format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

