project:
  type: website
  output-dir: docs

website:
  title: "Evaluación de Programas 2024"
  sidebar:
    background: primary
    logo: "iconoEvaluaciondeProgramasSociales.jpg"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/rojasirvin/evaluacion-de-programas
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: programa.qmd
        text: Programa
      - href: reglas.qmd
        text: Reglas
      - href: cronograma.qmd
        text: Cronograma
      - href: lecturas.qmd
        text: Lecturas
      - href: presentaciones.qmd
        text: Presentaciones
      - href: tareas/index.qmd
        text: Tareas

format:
  html:
    theme: minty
    css: styles.css
    toc: true

