---
title: "Presentaciones"
---

Por favor, seleccione una de las lecturas marcadas con una "+" de la lista de lecturas y envíe un correo al profesor para que se le asigne una fecha de presentación.

| **Autores** | **Tema** | **Presentador o presentadora** | **Fecha de exposición** |
| --- | --- | --- | --- |
| Arceo-Gomez & Campos-Vazquez (2014) | Experimental    | Rigoberto Mendoza | 6 de septiembre |
| Bruhn et al. (2018)  | Experimental    | Brian Roque | 6 de septiembre |
| Gertler (2004)  | Experimental    | Mariana Ruiz | 6 de septiembre |
|  Gonzalez-Navarro et al. (2016) | LATE    | Miguel Rosales | 20 de septiembre |
| De la O (2013)  | LATE    | Juan Carlos Muñoz | 20 de septiembre |
| Boruchowicz et al. (2022) | DID    | Rodrigo Gutiérrez | 4 de octubre |
|  Conti et al. (2023) | DID    | José Valencia | 4 de octubre |
|  Clarke & Mühlrad (2021) | DID    | Paola Guarneros | 4 de octubre |
| Espinosa & Rubin (2015) | PSM | Samuel Martínez   | 18 de octubre |
| Becerril et al. (2010)  | PSM    | Stephanie Neri | 18 de octubre |
|  García-Díaz et al. (2018) | PSM    | Francisco Vinicio  | 18 de octubre |
| Aguilar et al. (2021) | Discontinuidades  | Yorlyn Funez | 1 de noviembre |  
| Del Valle et al. (2020) | Discontinuidades  | Wolfgang Reséndiz | 1 de noviembre |
| Davis (2008) | Discontinuidades  | Alan Loera | 1 de noviembre |
| Campos-Vazquez & Esquivel (2023) | Control sintético  | Claudia Alemán | 13 de noviembre | 
|  | Control sintético  |  | 13 de noviembre | 
|  | Control sintético  |  | 13 de noviembre | 
| Chernozhukov et al. (2018)  | Machine Learning   | Jair García | 27 de noviembre | 
| Baiardi et al. (2021) | Machine Learning  | Raúl Cepeda | 27 de noviembre | 
|  | Machine Learning   |  | 27 de noviembre | 
