---
title: "Programa"
---


## Objetivos

*	Identificar las condiciones que permiten la implementación de una evaluación de impacto.
*	Conocer los fundamentos teóricos sobre los que se sustentan las metodologías de las evaluaciones de impacto.
*	Implementar los métodos de evaluación empleando software, interpretar los resultados y reportar las conclusiones en forma de artículos científicos y/o reportes de política.
*	Conocer e implementar buenas prácticas en el uso de software, orientadas a la transparencia y la replicabilidad en la investigación.
*	Conocer los temas que conforman la literatura actual de evaluaciones de impacto.


## Referencias

El curso se basa en los siguientes textos:

+ (MHE) Angrist, J.D. & Pischke, J.S. (2013). *Mostly Harmless Econometrics: An Empiricists Companion*. Princeton University Press.

+ (MM ) Angrist, J.D. & Pischke, J.S. (2014). *Mastering ’Metrics: The Path from Cause to Effect*. Princeton University Press.

+ (CT) Cameron, A.C. & P.K. Trivedi. (2005). *Microeconometrics: Methods and applications*. Oxford University Press.

+ (MT) Cunningham, S. (2021). Causal inference: The mixtape. Yale University Press. [Disponible en línea](https://mixtape.scunning.com/index.html).

+ Huntington-Klein, N. (2021). *The effect: An introduction to research design and causality*. Chapman and Hall/CRC.

+ DiNardo, J. & D.S. Lee. (2011). Program Evaluation and Research Designs. En *Handbook of Labor Economics*, 4A: 463-536.

+ (GMPRV) Gertler, P.J., S. Martinez, P. Premand, L.B., Rawlings, & C.M.J. Vermeersch. (2011). *La evaluación de impacto en la práctica*. Banco Interamericano de Desarrollo y Banco Mundial, segunda edición. [Disponible en línea](https://publications.iadb.org/publications/spanish/document/La-evaluaci%C3%B3n-de-impacto-en-la-pr%C3%A1ctica-Segunda-edici%C3%B3n.pdf).


## Contenido temático

Unidad 1. Introducción

* Fundamentos de la evaluación de impacto
  - Inferencia causal
  - Revisión de métodos de regresión
  
* Replicabilidad y transparencia en la evaluación
  - Quarto para la generación de reportes científicos

Unidad 2. Métodos de evaluación

* Evaluación experimental
  - Asignación aleatoria
  - Errores estándar
  - *LATE* y variables instrumentales
  - Corrección por prueba de múltiples hipótesis
  - Aplicaciones de métodos experimentales


* Diferencia en diferencias
  - Supuestos fundamentales
  - Efectos fijos individuales
  - DID desfasado
  - ANCOVA
  - Aplicaciones de DID

* Métodos de pareamiento
  - Supuestos fundamentales
  - Pareamiento exacto
  - Pareamiento por puntaje de propensión (PSM)
  - Aplicaciones del PSM

* Diseños con discontinuidades
  - Supuestos fundamentales
  - Discontinuidades nítidas y difusas
  - Discontinuidades geográficas
  - Pliegues en la regresión
  - Aplicaciones diseños con discontinuidades

* Método del control sintético
  - Supuestos fundamentales
  - Inferencia basada en placebos
  - Aplicaciones de control sintético

Unidad 3. Temas actuales de evaluación

* Extensiones I
  - Aprendizaje automatizado y _big data_ en la evaluación de impacto


## Evaluación del curso

+ Examen parcial: 20%
+ Examen final: 30%
+ Proyecto final: 20%
+ Tareas (4): 20% (5% cada una)
+ Exposición: 10% (7% presentación y 3% resumen)


## Tareas

Cuatro tareas teórico-prácticas. Las tareas deben entregarse de manera individual, pero se recomienda ampliamente colaborar en grupos de estudio. Para evitar confusiones, escriban en su tarea con quiénes colaboraron. Las tareas deberán entregarse en Teams antes de la fecha y hora señalada. No se aceptarán tareas fuera de tiempo. Por favor, **no comprima los archivos** en carpetas comprimidas. Las tareas deberán contener dos archivos:

Un primer documento de respuestas donde se incluyan las respuestas a las preguntas teóricas y conceptuales. Este documento debe estar en formato pdf y debe ser generado usando un software de procesamiento de textos científicos, por ejemplo, usando los leguajes LaTeX o Markdown. En este documento también se deben incluir las respuestas a preguntas sobre conclusiones que se desprenden de las secciones prácticas. Por ejemplo, si una pregunta pide obtener la media de la variable x en cierta base de datos, entonces el documento de respuestas debe incluir la pregunta y respuesta correspondiente: “la media de la variable x es 32.6”. En este documento también deberán incluirse las tablas y gráficas que se soliciten.

Un segundo archivo deberá contener el código replicable usado para generar los resultados de la sección práctica. El código debe también crear las tablas y gráficas solicitadas. Los archivos de código se verificarán para comprobar su replicabilidad.


## Software

R será el paquete standard usado en las sesiones prácticas. Más aún, el uso de cualquier software es aceptado siempre que se cumplan con los requisitos de replicabilidad y reportes de las tareas y exámenes. Habrá una sesión especial para introducir el uso de Quarto para la generación de reportes científicos.

## Exámenes
  
* Examen parcial: martes 1 de octubre en el horario de clase.

* Examen final: por definir.


## Exposiciones

Cada alumno realizará una presentación de uno los artículos aplicados marcados con “+” en la lista de lecturas. Cada presentación deberá ser de máximo 15 minutos y debe incluir el contenido que el presentador considere relevante. La presentación deberá abordar, mínimamente: 1) el problema a investigar, 2) la metodología empleada, 3) la pertinencia de la metodología y la teoría vista en el curso, 4) los datos empleados, 5) los principales resultados, y 6) una crítica sobre la validez y las conclusiones del estudio. La presentación deberá acompañarse de un breve resumen de máximo una página de extensión que sintetice los puntos anteriores, para ser distribuido con el resto de la clase.

## Proyecto final

El proyecto final consistirá en un protocolo de investigación de una evaluación de impacto. El tema y la metodología es libre, pero se evaluará el potencial para realizarse en el corto plazo. Se aconseja seleccionar un tema para el que se empleen datos de libre acceso. El protocolo deberá incluir, mínimamente: 1) una revisión de literatura, 2) un bosquejo de las motivaciones teóricas del problema, 3) la metodología empírica a emplear, 4) la fuente de datos a usar, y 5) los resultados preliminares. El proyecto debe presentarse en formato escrito con una extensión máxima de 20 cuartillas. Se recomienda ampliamente dar seguimiento al proyecto en horas de oficina para recibir retroalimentación respecto a los avances y resolver posibles dudas y dificultades.

Entrega: fecha por definir, a través de Teams.

## Lista de lecturas

Las lecturas obligatorias (marcadas con “*”) permiten una discusión informada en la clase. Las lecturas que serán presentadas en exposiciones también son obligatorias y están marcadas con “+”. El resto de las lecturas no serán cubiertas en clase, pero son ampliamente recomendables. En las sesiones de exposiciones se espera que el resto de la clase tenga el conocimiento suficiente sobre el material presentado para participar en la discusión.

La lista de lecturas está disponible [aquí](https://rojasirvin.github.io/evaluacion-de-programas/lecturas.html).
