---
title: "Tarea 1"
---

## Instrucciones

Fecha de entrega: **18 de septiembre**

La tarea deberá entregarse en Teams. Deberá incluir dos documentos:

Un primer documento de respuestas donde se incluyan las respuestas a las preguntas teóricas y conceptuales. Este documento debe estar en formato pdf y debe ser generado usando un software de procesamiento de textos científicos, por ejemplo, usando los leguajes LaTeX o Markdown. En este documento también se deben incluir las respuestas a preguntas sobre conclusiones que se desprenden de las secciones prácticas. Por ejemplo, si una pregunta pide obtener la media de la variable x en cierta base de datos, entonces el documento de respuestas debe incluir la pregunta y respuesta correspondiente: “la media de la variable x es 32.6”. En este documento también deberán incluirse las tablas y gráficas que se soliciten.

Un segundo archivo deberá contener el código replicable usado para generar los resultados de la sección práctica. El código debe también crear las tablas y gráficas solicitadas. Los archivos de código se verificarán para comprobar su replicabilidad.

## Datos

[muestra-enoe-123.csv](./files/muestra-enoe-123.csv) 
[STAR_public_use.csv](./files/STAR_public_use.csv)

## Pregunta 1

Suponga que para un experimento en un laboratorio de economía experimental se asignó a la mitad de los participantes a un grupo de tratamiento y la otra mitad al grupo de control. Se busca estudiar el efecto del tratamiento $T_i$ sobre el desempeño en un juego estratégico, medido por la variable $y_i$ (a más puntaje, mejor desempeño). Antes de comenzar el experimento se recolectaron una serie de características $x_{ji}$, $j=1,\ldots 10$, de cada jugador. En el experimento, se trabaja con $\alpha=0.10$.

a. [5 puntos] El investigador A quedó a cargo de comprobar el balance de la asignación del tratamiento y le reporta lo siguiente:

    *Para verificar que la aleatorización fue exitosa, tomé la serie de variables pre-intervención y la dummy de asignación al tratamiento $T_i$ para correr la siguiente regresión:*
$$T_i=\alpha+\sum_{j=1}^{10}x_{ji}'\beta +\varepsilon_i$$

    *Después realicé una prueba $F$ de significancia conjunta sobre los coeficientes $\beta_j$ que resultó tener un valor $p$ de 0.02.*

    Explique cuál es la hipótesis nula en la prueba realizada y qué se esperaría de haberse logrado una aleatorización exitosa del tratamiento.

b. [5 puntos] ¿Qué concluye a partir de lo que le reporta el investigador A?

a. [5 puntos] Por otro lado, el investigador B le reporta lo siguiente:

    *Yo realicé un análisis para determinar el balance en la asignación del tratamiento. Para cada una de las características $x_{ji}$ corrí la siguiente regresión:*
$$x_{ji}=\gamma+\pi T_i+u_i$$
*A continuación, le reporto una tabla con los valores $p$ asociados al coeficiente estimado de $\pi$ en cada una de las 10 regresiones.*

    | **Característica** |	**Valor $p$** || **Característica** |	**Valor $p$**
    |--- | --- |---|---|---|
    | $x_{1i}$	| 0.05 | |$x_{6i}$	| 0.03 |
    | $x_{2i}$	| 0.02 | |$x_{7i}$	| 0.19 |
    | $x_{3i}$	| 0.07 | |$x_{8i}$	| 0.85 |
    | $x_{4i}$	| 0.00 | |$x_{9i}$	| 0.01 |
    | $x_{5i}$	| 0.42 | |$x_{10i}$	| 0.03 |
    
    Explique la hipótesis nula detrás de las pruebas que realizó el investigador B y qué se esperaría de haberse logrado una aleatorización exitosa del tratamiento,

a. [5 puntos] Explique qué concluye sobre la validez interna del estudio en cuestión. ¿Qué propiedades estadísticas tendría el estimador de diferencia de medias de la variable de desempeño en el juego entre el grupo tratado y el de control?


## Pregunta 2

Suponga que está interesado en conocer el impacto que tiene el acceso a las microfinanzas en un indicador de seguridad alimentaria $y_i$ de las familias. La idea detrás es que el acceso al crédito podría mejorar la habilidad de los hogares para suavizar el consumo. Afortunadamente, usted recibe el respaldo de una microfinanciera que le ofrece una base de datos para con información para construir $y_i$, recolecatada a partir de una encuesta en los hogares de sus clientes con más de un año de antiguedad. Además, le da acceso a datos de otra encuesta complementaria realizada en hogares que no son clientes y que no tienen acceso a microfinanzas para construir el mismo indicador de seguridad alimentaria. Al final, tendría una muestra de varios miles de hogares con y sin acceso a microfinanzas.

Suponga que con estos datos descubre que la seguridad alimentaria es 25% más alta en los hogares con clientes de la microfinanciera, en comparación con la seguridad alimentaria de los hogares sin acceso a las microfinanzas.

a. [10 puntos] ¿Cómo valora el diseño del estudio descrito? ¿Qué fortalezas y/o debilidades encuentra? 

a. [10 puntos] ¿De qué signo esperaría que fuera el sesgo de selección, en caso de existir? Explique sus razones.

## Pregunta 3

Replique el ejercicio de representar la FEC de salarios en función de educación para México, como en la Figura 3.1.1 de MHE (p. 39), usando los datos del primer trimestre de 2023 de la ENOE. El gráfico es complejo, pero recibirá crédito completo si reproduce, al menos por separado, los dos siguientes tipos de gráficos:

a.	[10 puntos] Replique el ejercicio en MHE que ejemplifica el teorema de la regresión de la FEC. Para esto use el archivo de datos *muestra-enoe-123.csv*, que contiene una muestra del primer trimestre de 2023 de la ENOE e incluye personas que trabajan y reciben un ingreso. **lingreso** es el log del ingreso mensual y **escolaridad** son los años de educación. Primero, estime una regresión de **lingreso** en función de **escolaridad** usando los microdatos. Luego, obtenga la media de **lingreso** para cada nivel de **escolaridad** y estime una regresión de las medias en función de **escolaridad**, pesando por el número de observaciones usadas para construir cada media. Compare los coeficientes estimados.


## Pregunta 4

Use los datos del archivo *STAR_public_use.csv* para este problema. En este problema replicará la columna 1 de la Tabla 1 en [Angrist et al. (2009)](https://pubs.aeaweb.org/doi/pdfplus/10.1257/app.1.1.136).[^1]
  
[^1]: Angrist, J., Lang, D., y Oreopoulos, P. (2009). Incentives and services for college achievement: Evidence from a randomized trial. *American Economic Journal: Applied Economics*, 1(1), 136-63.

a. [5 puntos] Obtenga la media y la desviación estándar de la edad, **age**, en el grupo de control (columna 1), restringiendo la muestra a aquellos individuos con **noshow** igual a 0.

a. [10 puntos] Usando una regresión lineal, muestre que la edad no está correlacionada con la asignación a los tratamientos (**ssp**, **sfp** y **sfsp**). De nuevo, debe restringir la muestra quienes tienen **noshow** igual a 0. Reporte los coeficientes y los errores estándar (columnas 2 a 4).

a. [5 puntos] Realice una prueba de significancia conjunta de los coeficientes obtenidos en el punto b. Reporte el estadístico $F$ y el valor $p$ asociado (columna 5).

a. [10 puntos] ¿Cuál es el propósito de la prueba F realizada en el punto c.? ¿Qué hipótesis nula prueban los autores?

## Pregunta 5

Nuevamente, use los datos del archivo *STAR_public_use.csv* para este problema. En este problema, replicará dos columnas del efecto de tratamiento de la Tabla 5. Note que de nuevo se deben usar solo las observaciones que tienen **noshow** igual a 0. Además, note que se usan las siguientes variables de control: **sex**, **mtongue**, **hsgroup**, **numcourses_nov1**, **lastmin**, **mom_edn**, y **dad_edn**, todas ellas categóricas.

Antes de estimar los efectos, los autores sustituyen **gpa_year1** por *NA* cuando **grade_20059_fall** es *NA* y sustituyen **grade_20059_fall** por *NA* cuando **gpa_year1** es *NA* Esto le permitirá quedarse con los individuos que tienen información completa.

a. [10 puntos] Estime el efecto de cada tipo de tratamiento sobre el *GPA*, es decir, sobre la variable **gpa_year1**, para toda la muestra (Panel B, columna 1). Calcule correctamente los errores estándar. Interprete los resultados.

a. [10 puntos] Estime el efecto de recibir cada tipo de tratamiento, considerando los tratamientos SSP o SFP (de cualquier tipo) en las mujeres de la muestra (Panel B, columna 6). Esto es, considere el tratamiento SSP como un primer tipo de tratamiento y, ya sea SFP o SFSP, como un segundo tipo de tratamiento. Calcule correctamente los errores estándar. Interprete sus resultados.
