---
title: "Tarea 1"
lang: es
format: html
---

```{r setup}
#| echo: false
#| warning: false 
#| message: false
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
library(tidyverse)
library(knitr)
library(janitor)
library(readr)
library(kableExtra)
library(stargazer)
library(sandwich)
library(lmtest)
library(gt)
library(gtExtras)
```


## Preguntas

Fecha de entrega: **lunes 15 de septiembre a las 20:00 en Teams**

La tarea deberá entregarse en Teams. Deberá incluir dos documentos:

Un primer documento de respuestas donde se incluyan las respuestas a las preguntas teóricas y conceptuales. Este documento debe estar en formato pdf y debe ser generado usando un software de procesamiento de textos científicos, por ejemplo, usando los leguajes LaTeX o Markdown. En este documento también se deben incluir las respuestas a preguntas sobre conclusiones que se desprenden de las secciones prácticas. Por ejemplo, si una pregunta pide obtener la media de la variable x en cierta base de datos, entonces el documento de respuestas debe incluir la pregunta y respuesta correspondiente: “la media de la variable x es 32.6”. En este documento también deberán incluirse las tablas y gráficas que se soliciten.

Un segundo archivo deberá contener el código replicable usado para generar los resultados de la sección práctica. El código debe también crear las tablas y gráficas solicitadas. Los archivos de código se verificarán para comprobar su replicabilidad.

## Datos

[muestra-enoe-123.csv](../files/muestra-enoe-123.csv)

[STAR_public_use.csv](../files/STAR_public_use.csv)


## Pregunta 1

Suponga que para un experimento en un laboratorio se asignó a un grupo pacientes a un brazo de tratamiento o a uno de control. Antes de comenzar el experimento se recolectaron una serie de características $x_{ji}$, $j=1,\ldots 10$, de cada paciente. Se busca medir el efecto del tratamiento sobre una variable de resultados $y_i$. En el experimento, se trabaja con $\alpha=0.10$.

a. [5 puntos] El investigador A quedó a cargo de comprobar el balance de la asignación del tratamiento y le reporta lo siguiente:

    *Para verificar que la aleatorización fue exitosa, tomé la serie de variables pre-intervención y la dummy de asignación al tratamiento $T_i$ para correr la siguiente regresión:*
$$T_i=\alpha+\sum_{j=1}^{10}x_{ji}'\beta +\varepsilon_i$$

    *Después realicé una prueba $F$ de significancia conjunta sobre los coeficientes $\beta_j$ que resultó tener un valor $p$ de 0.043.*

    Explique cuál es la hipótesis nula en la prueba realizada y qué se esperaría de haberse logrado una aleatorización exitosa del tratamiento.

b. [5 puntos] ¿Qué concluye a partir de lo que le reporta el investigador A?

a. [5 puntos] Por otro lado, el investigador B le reporta lo siguiente:

    *Yo realicé un análisis para determinar el balance en la asignación del tratamiento. Para cada una de las características $x_{ji}$ corrí la siguiente regresión:*
$$x_{ji}=\gamma+\pi T_i+u_i$$
*A continuación, le reporto una tabla con los valores p asociados al coeficiente estimado de $\pi$ en cada una de las 10 regresiones.*

    | **Característica** |	**Valor $p$** || **Característica** |	**Valor $p$**
    |--- | --- |---|---|---|
    | $x_{1i}$	| 0.025 | |$x_{6i}$	| 0.015 |
    | $x_{2i}$	| 0.012 | |$x_{7i}$	| 0.033 |
    | $x_{3i}$	| 0.027 | |$x_{8i}$	| 0.019 |
    | $x_{4i}$	| 0.076 | |$x_{9i}$	| 0.028 |
    | $x_{5i}$	| 0.002 | |$x_{10i}$	| 0.017 |
    
    Explique la hipótesis nula detrás de las pruebas que realizó el investigador B y qué se esperaría de haberse logrado una aleatorización exitosa del tratamiento,

a. [5 puntos] ¿Cómo reconcilia la evidencia encontrada por el investigador A y el B y qué concluye sobre el balance en la asignación del tratamiento? ¿Qué características tendría una diferencia de medias de $y_i$ después del tratamiento como estimador del impacto de este?


## Pregunta 2

Suponga que está interesado en conocer el impacto que tiene el acceso a las microfinanzas en un indicador de seguridad alimentaria $y_i$ de las familias. La idea detrás es que el acceso al crédito podría mejorar la habilidad de los hogares para suavizar el consumo. Afortunadamente, usted tiene acceso a una encuesta representativa a nivel nacional que incluye un índice de seguridad alimentaria así como una variable indicadora o *dummy*, $T_i$, que toma el valor de 1 si algún miembro del hogar tiene acceso a microfinanzas y de 0 en otro caso.

Suponga que su asistente le sugiere que para evaluar el impacto de microfinanzas basta con estimar la siguiente regresión por MCO:

$$ y_i = \alpha + \beta T_i + \varepsilon_i $$

a. [5 puntos] ¿Cómo valora la propuesta de su asistente? ¿Qué podemos esperar de una comparación observacional como la de la propuesta?

a. [5 puntos] Muestre si el estimador de MCO de $\beta$ es consistente o no para el efecto de tratamiento.

## Pregunta 3

[10 puntos] Replique el ejercicio en MHE que ejemplifica el teorema de la regresión de la FEC. Para esto use el archivo de datos *muestra-enoe-123.csv*, que contiene una muestra del primer trimestre de 2023 de la ENOE e incluye personas que trabajan y reciben un ingreso. **lingreso** es el log del ingreso mensual y **escolaridad** son los años de educación. Primero, estime una regresión de **lingreso** en función de **escolaridad** usando los microdatos. Luego, obtenga la media de **lingreso** para cada nivel de **escolaridad** y estime una regresión de las medias en función de **escolaridad**, pesando por el número de observaciones usadas para construir cada media. Compare los coeficientes estimados.


## Pregunta 4

Use los datos del archivo *STAR_public_use.csv* para este problema. En este problema replicará la fila correspondiente a la variable *Age* (edad del o la estudiante) de la Tabla 1 en [Angrist et al. (2009)](https://pubs.aeaweb.org/doi/pdfplus/10.1257/app.1.1.136).[^1]
  
[^1]: Angrist, J., Lang, D., y Oreopoulos, P. (2009). Incentives and services for college achievement: Evidence from a randomized trial. *American Economic Journal: Applied Economics*, 1(1), 136-63.

a. [5 puntos] Obtenga la media y la desviación estándar de la edad, **age** en los datos, en el grupo de control (columna 1), restringiendo la muestra a aquellos individuos con **noshow** igual a 0.

a. [10 puntos] Usando una regresión lineal, muestre que la edad no está correlacionada con la asignación a los tratamientos (**ssp**, **sfp** y **sfsp**). De nuevo, debe restringir la muestra quienes tienen **noshow** igual a 0. Reporte los coeficientes y los errores estándar (columnas 2 a 4).

a. [5 puntos] Realice una prueba de significancia conjunta de los coeficientes obtenidos en el punto b. Reporte el estadístico $F$ y el valor $p$ asociado (columna 5).

a. [10 puntos] ¿Cuál es el propósito de la prueba F realizada en el punto c.? ¿Qué hipótesis nula prueban los autores?

## Pregunta 5

Nuevamente, use los datos del archivo *STAR_public_use.csv* para este problema. En este problema, replicará dos columnas del efecto de tratamiento de la Tabla 5. Note que de nuevo se deben usar solo las observaciones que tienen **noshow** igual a 0. Los autores también sustituyen los valores de **gpa_year1** por *NA* cuando la variable **grade_20059_fall** es *NA*; y sustituyen **grade_20059_fall** por *NA* cuando la variable **gpa_year1** es *NA.* Además, note que se usan las siguientes variables de control: **sex**, **mtongue**, **hsgroup**, **numcourses_nov1**, **lastmin**, **mom_edn**, y **dad_edn**, todas ellas categóricas.

a. [10 puntos] Estime el efecto de cada tipo de tratamiento sobre el promedio o *GPA*, denotado **gpa_year1** en los datos, para toda la muestra (Panel B, columna 1). Calcule correctamente los errores estándar. Interprete los resultados.

a. [10 puntos] Estime el efecto sobre el *GPA* de recibir cada tipo de tratamiento, considerando los tratamientos SSP o SFP (de cualquier tipo) en los hombres de la muestra (Panel B, columna 5). Esto es, considere el tratamiento SSP como un primer tipo de tratamiento y, ya sea SFP o SFSP, como un segundo tipo de tratamiento. Calcule correctamente los errores estándar. Interprete sus resultados.
