<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-contrib/bootstrap-icons-1.13.1/bootstrap-icons.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>Inferencia Causal 2025 – clase_4</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-8b940f0b0c37e8b60983ca0a0adffd2d.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>

  <link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section id="clase-4.-regresión-y-efectos-causales" class="title-slide slide level1 portada center">
<h1>Clase 4. Regresión y efectos causales</h1>
<div style="text-align: center; font-size: 1.2em; font-weight: bold;">
<p>Inferencia Causal</p>
</div>
<div style="text-align: center; margin-top: 1em;">
<p><strong>Irvin Rojas</strong><br>
<br> <a href="https://rojasirvin.com" style="color: #ffffff;">rojasirvin.com</a></p>
</div>
<div style="text-align: center; margin-top: 1em;">
<p><a href="https://github.com/rojasirvin" target="_blank" style="margin-right: 0 10px;"> <i class="bi-github " style="" role="img" aria-hidden="true"></i> </a> <a href="https://twitter.com/RojasIrvin" target="_blank" style="margin-right: 0 10px;"> <i class="bi-twitter " style="" role="img" aria-hidden="true"></i> </a> <a href="https://scholar.google.com/citations?user=FUwdSTMAAAAJ&amp;hl=en" style="margin: 0 10px;"> <i class="bi-google " style="" role="img" aria-hidden="true"></i> </a></p>
</div>
<p><strong>Centro de Investigación y Docencia Económicas</strong> División de Economía</p>
</section>

<section id="agenda" class="title-slide slide level1 center">
<h1>Agenda</h1>
<ol type="1">
<li><p>Motivar el uso de regresión para el análisis de efectos de tratamiento</p></li>
<li><p>Estudiaremos el supuesto de independencia condicional</p></li>
<li><p>Veremos un ejemplo de experimento aleatorio para relacionarlo con lo que ya sabemos y para identificar elementos que iremos descubriendo con el tiempo</p></li>
</ol>
</section>

<section id="motivación-del-uso-de-regresión-en-evaluación" class="title-slide slide level1 inverse center middle">
<h1>Motivación del uso de regresión en evaluación</h1>

</section>

<section id="regresión-como-función-de-esperanza-condicional" class="title-slide slide level1 center">
<h1>Regresión como función de esperanza condicional</h1>
<ul>
<li><p>Olvidemos por ahora la causalidad y centremonos en la conexión entre dos variables, <span class="math inline">\(y\)</span> y <span class="math inline">\(s\)</span> (ingreso y educación)</p></li>
<li><p>La <strong>función de esperanza condicional</strong> es una forma de describir la relación entre estas dos variables</p></li>
<li><p><strong>Función de esperanza condicional</strong>: la FEC de <span class="math inline">\(y_i\)</span> dado un vector de regresores <span class="math inline">\(X_i\)</span> es la esperanza o promedio poblacional de <span class="math inline">\(y_i\)</span> cuando mantenemos fijo <span class="math inline">\(X_i\)</span> y se denota <span class="math inline">\(E(y_i|X_i)\)</span></p></li>
<li><p>Para representar una realización particular de <span class="math inline">\(X_i\)</span> escribimos <span class="math inline">\(X_i=x_i\)</span>, por lo que la FEC es <span class="math inline">\(E(y_i|X_i=x_i)\)</span></p></li>
<li><p>Con <span class="math inline">\(y_i\)</span> discreta, la FEC se expresa como</p></li>
</ul>
<p><span class="math display">\[E(y_i|X_i=x_i)=\sum_t t P(y_i=t|X_i=x_i)\]</span></p>
</section>

<section id="ejemplo-de-fec-salarios-y-educación-en-estados-unidos" class="title-slide slide level1 center">
<h1>Ejemplo de FEC: salarios y educación en Estados Unidos</h1>
<div class="columns">
<div class="column" style="width:&quot;50%;">
<ul>
<li>La figura 3.3.1 en MHE muestra la FEC de salarios en Estados Unidos</li>
<li>Para cada año de educación, vemos cuál es el (log) del ingreso semanal</li>
<li>La figura muestra dos cosas principales:
<ul>
<li>La clara relación positiva entre salarios y educación</li>
<li>La gran variabilidad en salarios para un nivel de educación dado</li>
</ul></li>
</ul>
</div><div class="column" style="width:&quot;50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/fec_mhe.png" style="width:100.0%"></p>
<figcaption>Fuente: Angrist &amp; Pischke (2009)</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>

<section id="teorema-de-la-regresión-de-la-fec" class="title-slide slide level1 center">
<h1>Teorema de la regresión de la FEC</h1>
<ul>
<li>MHE provee varias motivaciones de usar regresión al relacionar la función de regresión con la FEC</li>
<li>Aquí vamos a rescatar el que considero más intuitivo</li>
<li><strong>Teorema de la regresión de la FEC</strong>: la función <span class="math inline">\(X_i'\beta\)</span> es la aproximación lineal de mínimos errores cuadrados promedio de <span class="math inline">\(E(y_i|X_i)\)</span>: <span class="math display">\[\beta=\arg\min_b E((E(y_i|X_i)-X_i'b) ^2)\]</span></li>
<li>Lo que nos dice este teorema es que si yo quiero <strong>aproximar</strong> la FEC y mi criterio para obtener la mejor aproximación es un problema de mínimos cuadrados promedio, entonces lo mejor que puedo hacer es que mi aproximación sea <span class="math inline">\(X'\beta\)</span></li>
</ul>
</section>

<section id="teorema-de-la-regresión-de-la-fec-1" class="title-slide slide level1 center">
<h1>Teorema de la regresión de la FEC</h1>
<ul>
<li>Este teorema nos dice que si pensamos en en aproximar <span class="math inline">\(E(y_i|X_i)\)</span>, incluso aunque la FEC no sea lineal, la función de regresión nos da la mejor aproximación lineal</li>
<li>Este teorema es lo más cercano a como interpretamos la regresión en evaluación pues más que querer predicciones de <span class="math inline">\(y\)</span> para un individuo <span class="math inline">\(i\)</span>, nos interesa la relación promedio entre las variables</li>
<li>Vale la pena notar que aquí hablamos de la función de regresión <strong>poblacional</strong>, es decir, aún tenemos que hablar sobre cómo estimarla</li>
</ul>
</section>

<section id="teorema-de-la-regresión-de-la-fec-2" class="title-slide slide level1 center">
<h1>Teorema de la regresión de la FEC</h1>
<div class="columns">
<div class="column" style="width:&quot;50%;">
<ul>
<li>La figura 3.1.2 en MHE ilustra este teorema</li>
<li>La línea sólida es la FEC de la relación años de educación - salario</li>
<li>La línea sólida muestra los promedios del salario para cada año de educación</li>
<li>La línea quebrada muestra la línea de regresión usando microdatos
<ul>
<li>Graficar el coeficiente <span class="math inline">\(\beta\)</span> que resulta al correr <span class="math inline">\(y_i=\alpha+\beta s_i+u_i\)</span></li>
</ul></li>
<li>El teorema de la regresión de la FEC dice que obtenemos la misma recta si hacemos una regresión de <span class="math inline">\(E(y_i|s_i)=\alpha+\beta s +u\)</span></li>
</ul>
</div><div class="column" style="width:&quot;50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figures/regresion_fec_mhe.png" style="width:80.0%"></p>
<figcaption>Fuente: Angrist &amp; Pischke (2009)</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>Es decir, calculamos las medias del salario para cada nivel de educación y luego se hacemos una regresión de las medias en función de los niveles de educación (dándole más peso a las observaciones que aportaron más datos a la media de cada nivel)</li>
</ul>
</div></div>
</section>

<section id="modelos-saturados" class="title-slide slide level1 center">
<h1>Modelos saturados</h1>
<ul>
<li><p>Son modelos de regresión donde incluimos una variable categórica para cada uno de los posibles valores que tomen las <span class="math inline">\(X_i\)</span></p></li>
<li><p>Del ejemplo con los datos de EUA, hay 21 posibles años de educación, entonces un modelo saturado es:</p></li>
</ul>
<p><span class="math display">\[y_i=\alpha+\beta_1 c_{1i} + \beta_2 c_{2i} + \ldots + \beta_{21} c_{21i} + u_i\]</span> donde <span class="math inline">\(c_{ji}=1\)</span> si el individuo <span class="math inline">\(i\)</span> tiene una educación <span class="math inline">\(s_{i}=j\)</span></p>
<div class="fragment">
<ul>
<li>El <span class="math inline">\(j\)</span>-ésimo coeficiente <span class="math inline">\(\beta_j\)</span> es el efecto de tener el nivel de educación <span class="math inline">\(j\)</span></li>
<li>Además, <span class="math inline">\(\alpha=E(y_i|s_i=0)\)</span>, se conoce como la categoría omitida</li>
<li>Podemos escoger la categoría omitida que tenga más sentido</li>
</ul>
</div>
</section>

<section id="modelos-saturados-1" class="title-slide slide level1 center">
<h1>Modelos saturados</h1>
<ul>
<li>Si tuviéramos dos características, sexo y urbano-rural, un modelo saturado incluye un <em>término interacción</em>:</li>
</ul>
<p><span class="math display">\[y_i=\alpha+\beta_H x_{Hi} + \beta_R x_{Ri}+ \beta_{HR} x_{Hi}x_{Ri}+u_i\]</span></p>
<ul>
<li><p>A los coeficientes <span class="math inline">\(\beta_H\)</span> y <span class="math inline">\(\beta_U\)</span> se les conoce como <em>efectos principales</em></p></li>
<li><p>El término de interacción <span class="math inline">\(\beta_{HR}\)</span> nos dice cómo cambia el ingreso entre individuos por tipo de localidad y por sexo</p></li>
</ul>
<div class="fragment">
<ul>
<li>Un modelo saturado, si usamos sexo y <span class="math inline">\(\tau\)</span> categorías de educación, sería: <span class="math display">\[y_i=\alpha+\beta_H x_{Hi}+\sum_{j=1}^{\tau} \beta_j c_{ji} + \sum_{j=1}^{\tau}\beta_{Hj}(x_{Hi}c_{ji})  + u_i\]</span></li>
</ul>
</div>
</section>

<section id="regresión-y-causalidad" class="title-slide slide level1 inverse center middle">
<h1>Regresión y causalidad</h1>

</section>

<section id="regresión-y-causalidad-1" class="title-slide slide level1 center">
<h1>Regresión y causalidad</h1>
<ul>
<li><p>Lo que hemos visto hasta ahora nos dice que la regresión es nuestro mejor aproximación lineal a la FEC</p></li>
<li><p>Pero la regresión será causal solo si la FEC es causal</p></li>
<li><p>Con lo que hemos visto del modelo de resultados potenciales, podemos tener una interpretación causal de la FEC</p></li>
</ul>
<div class="fragment">
<ul>
<li>La <strong>FEC es causal</strong> cuando describe las diferencias en resultados potenciales promedio para una población de referencia fija (Angrist and Pischke, 2009)</li>
<li>En la relación entre educación y salarios, una FEC causal describiría lo que un individuo ganaría con distintos niveles de educación</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Hay otro caso en el que la regresión puede tener interpretación causal, cuando existe <strong>selección basada en observables</strong></li>
</ul>
</div>
</section>

<section id="supuesto-de-independencia-condicional" class="title-slide slide level1 center">
<h1>Supuesto de independencia condicional</h1>
<ul>
<li>El <strong>supuesto de independencia condicional</strong> significa que, condicional en una serie de características <span class="math inline">\(X_i\)</span>, el sesgo de selección desaparece:</li>
</ul>
<p><span class="math display">\[\{y_{0i},y_{1i}\}\perp D_i | X_i\]</span></p>
<div class="fragment">
<ul>
<li>Supongamos que <span class="math inline">\(D_i\)</span> es ir o no a la universidad y la variable de interés es el ingreso</li>
<li>Sabemos que la comparación observacional nos da:</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
E(y_i|D_i=1)-E(y_i|D_i=0)=&amp;\overbrace{ E(y_{1i}-y_{0i}|D_i=1)}^{\text{Efecto promedio en los tratados}}+\\&amp; \underbrace{E(y_{0i}|D_i=1)-E(y_{oi}|D_i=0)}_{\text{Sesgo de selección}}
\end{aligned}
\]</span></p>
<ul>
<li>Es posible que aquellos que no fueron a la universidad de todos modos hubieran tenido un mayor salario, por lo que el sesgo de selección es positivo</li>
</ul>
</div>
</section>

<section id="supuesto-de-independencia-condicional-1" class="title-slide slide level1 center">
<h1>Supuesto de independencia condicional</h1>
<ul>
<li><p>El SIC implica que si hacemos la comparación condicional en <span class="math inline">\(X_i\)</span>, el sesgo desaparece <span class="math display">\[
\begin{aligned}
E(y_i|X_i,D_i=1)-E(y_i|X_i,D_i=0)=E(y_{1i}-y_{0i}|X_i)
\end{aligned}
\]</span></p></li>
<li><p>Es decir, que si comparamos a personas con y sin tratamiento, con los <span class="math inline">\(X_i\)</span> <em>fijos</em>, el sesgo de selección desaparece</p></li>
<li><p><em>Mantener fijas</em> las <span class="math inline">\(X\)</span> es el análogo a obtener el promedio del salario en cada nivel de escolaridad en la gráfica de la FEC descrita anteriormente</p></li>
</ul>
</section>

<section id="supuesto-de-independencia-condicional-2" class="title-slide slide level1 center">
<h1>Supuesto de independencia condicional</h1>
<ul>
<li><p>Para generalizar el concepto cuando la variable tiene más de dos valores (como con la educación <span class="math inline">\(s_i\)</span>), escribamos <span class="math inline">\(Y_{si}\equiv f_i(s)\)</span></p></li>
<li><p>Esta función nos dice cuál sería el ingreso de <span class="math inline">\(i\)</span> bajo todos los posibles niveles de <span class="math inline">\(s\)</span></p></li>
<li><p>En este caso, asumimos el SIC, que se traduce en:</p></li>
</ul>
<p><span class="math display">\[Y_{si}\perp s_i | X_i\]</span> - En diseños experimentales, el SIC surge porque el tratamiento se asigna de forma aleatoria - Pero con datos <em>observacionales</em>, el SIC significa que <span class="math inline">\(s_i\)</span> es <em>casi como si fuera asignado de manera aleatoria</em> cuando condicionamos en <span class="math inline">\(X_i\)</span></p>
</section>

<section id="supuesto-de-independencia-condicional-3" class="title-slide slide level1 center">
<h1>Supuesto de independencia condicional</h1>
<ul>
<li>En los datos solo observamos <span class="math inline">\(Y_i=f_i(s_i)\)</span></li>
<li>Dado el SIC, podemos hacer comparaciones de ingreso promedio para distintos niveles de educación: <span class="math display">\[E(Y_i|X_i,s_i=s)-E(Y_i|X_i,s_i=s-1)=E(f_i(s)-f_i(s-1)|X_i)\]</span></li>
</ul>
<div class="fragment">
<ul>
<li>Notemos que lo impráctico de esto es que tendríamos que hacer comparaciones en pares y luego tratar de hacer un promedio ponderado por el número de individuos en cada nivel de educación</li>
</ul>
</div>
</section>

<section id="regresión-para-hacer-las-comparasiones" class="title-slide slide level1 center">
<h1>Regresión para hacer las comparasiones</h1>
<ul>
<li>Supongamos una función causal para el ingreso <span class="math display">\[f_i(s)=\alpha+\rho s+\nu_i\]</span></li>
</ul>
<p>que indica lo que un individuo ganaría para todo valor de <span class="math inline">\(s\)</span> (y no solo el valor realizado <span class="math inline">\(s_i\)</span>)</p>
<ul>
<li><p>La única parte aleatoria es el error con media cero <span class="math inline">\(\nu_i\)</span>, que captura los factores no observados que afectan los ingresos</p></li>
<li><p>Sustituyendo el valor observado:</p></li>
</ul>
<p><span class="math display">\[Y_i=\alpha+\rho s_i+\nu_i\]</span></p>
<ul>
<li><span class="math inline">\(s_i\)</span> puede estar correlacionado con los resultados potenciales <span class="math inline">\(f_i(s)\)</span>, es decir, correlacionado con el error <span class="math inline">\(\nu_i\)</span></li>
</ul>
</section>

<section id="regresión-para-hacer-las-comparasiones-1" class="title-slide slide level1 center">
<h1>Regresión para hacer las comparasiones</h1>
<ul>
<li><p>Supongamos que el SIC se cumple dado un vector <span class="math inline">\(X_i\)</span></p></li>
<li><p>Descompongamos el error en una función lineal de las características <span class="math inline">\(X_i\)</span> y un error <span class="math inline">\(u_i\)</span>: <span class="math display">\[\nu_i=X_i'\gamma+u_i\]</span></p></li>
</ul>
<p>donde se asume que <span class="math inline">\(E(\nu_i|X_i)=X_i'\gamma\)</span> y donde <span class="math inline">\(u_i\)</span> y <span class="math inline">\(X_i\)</span> no están correlacionados</p>
<ul>
<li>Si se cumple el SIC, entonces:</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
E(f_i(s)|X_i,s_i)=E(f_i(s)|X_i)&amp;=\alpha+\rho s+E(\nu_i|X_i) \\
&amp;=\alpha+\rho s + X_i'\gamma
\end{aligned}
\]</span></p>
<ul>
<li><p>Es decir, en el modelo de regresión causal <span class="math inline">\(Y_i=\alpha+\rho s_i+ X_i'\gamma+u_i\)</span>, <span class="math inline">\(u_i\)</span> no está correlacionado con los regresores <span class="math inline">\(X_i\)</span> y <span class="math inline">\(s_i\)</span></p></li>
<li><p><span class="math inline">\(\rho\)</span> es el efecto causal de interés</p></li>
<li><p>El supuesto clave es que la única razón por la cual <span class="math inline">\(\nu_i\)</span> y <span class="math inline">\(s_i\)</span> están correlacionados es <span class="math inline">\(X_i\)</span></p></li>
</ul>
</section>

<section id="en-resumen" class="title-slide slide level1 center">
<h1>En resumen</h1>
<ul>
<li><p>Las comparaciones observacionales están contaminadas por el sesgo de selección</p></li>
<li><p>La aleatorización resuelve el problema de selección, es decir, al comparar la variable de resultados de interés entre individuos tratados y no tratados, obtenemos el efecto causal</p></li>
<li><p>La FEC nos ayuda a describir la relación entre dos variables, por ejemplo, entre el estado de tratamiento y la variable de resultados</p></li>
<li><p>La regresión es una aproximación lineal a la FEC, aún cuando la FEC no sea lineal</p></li>
<li><p>Usaremos regresión como una herramienta para <strong>comparar</strong> la variable de resultados entre grupos</p></li>
<li><p>La regresión tiene una interpretación causal si la FEC que trata de aproximar es cauusal</p></li>
<li><p>El SIC le da una interpretación causal a la regresión, pero el SIC es un supuesto fuerte</p></li>
</ul>
</section>

<section id="aplicación-efectivo-o-condicionales" class="title-slide slide level1 inverse center middle">
<h1>Aplicación: efectivo o condicionales</h1>

</section>

<section id="qué-tipo-de-programa-funciona-mejor" class="title-slide slide level1 center">
<h1>¿Qué tipo de programa funciona mejor?</h1>
<ul>
<li><p>Baird, S., McIntosh, C., &amp; Özler, B. (2011). Cash or condition? Evidence from a cash transfer experiment</p></li>
<li><p>¿Cuál es la diferencia entre un CCT y un UCT?</p></li>
<li><p>¿Cuál es la racionalidad económica de los CCT?</p>
<ul>
<li><p>Fallas de mercado</p></li>
<li><p>Información asimétrica o incompleta</p></li>
<li><p>Factibilidad política</p></li>
</ul></li>
<li><p>Críticas a los CCT</p></li>
</ul>
</section>

<section id="el-experimento-ideal" class="title-slide slide level1 center">
<h1>El experimento ideal</h1>
<ul>
<li>Si queremos saber qué funciona mejor, ¿cuál es el experimento ideal?</li>
</ul>
<div class="fragment">
<ul>
<li><p>Ya hemos visto varios elementos para interpretar los resultados del trabajo</p>
<ul>
<li><p>Integridad del diseño</p></li>
<li><p>Efectos de tratamiento usando regresiones</p></li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p>Este artículo contiene muchos elementos que no hemos visto, pero veremos cómo a lo largo del curso nos haremos de herramientas para entender la literatura</p>
<ul>
<li><p><span class="math inline">\(z\)</span>-scores</p></li>
<li><p>Interpretación de <em>complidores</em> y <em>no cumplidores</em></p></li>
<li><p>Errores agrupados</p></li>
</ul></li>
</ul>
</div>
</section>

<section id="el-programa" class="title-slide slide level1 center">
<h1>El programa</h1>
<ul>
<li>¿En qué consiste?</li>
</ul>
<div class="fragment">
<ul>
<li><p>Condicionales en el brazo CCT</p></li>
<li><p>Sin requerimientos de asistencia escolar en el brazo UCT</p></li>
</ul>
</div>
<div class="fragment">
<ul>
<li><p>Lugar de implementación: Malawi, distrito de Zomba</p></li>
<li><p>550 áreas de enumeración (EA) con aproximadamente 250 hogares cada una</p></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>¿A qué nivel se asginó el tratamiento?</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Se seleccionaron 176 EA para el estudio: 46 en CCT, 27 en UCT y 88 en C</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>¿Quiénes fueron elegibles?
<ul>
<li>Mujeres de 13-22 años</li>
<li>Nunca han estado casadas</li>
<li>Criterio de escolaridad</li>
</ul></li>
</ul>
</div>
</section>

<section id="datos" class="title-slide slide level1 center">
<h1>Datos</h1>
<ul>
<li><p>Encuesta anual para obtener <span class="math inline">\(X\)</span></p></li>
<li><p>En la R2 encuesta a todas las escuelas</p></li>
<li><p>En la R3 encuesta a una submuestra</p></li>
<li><p>Lista de asistencia</p></li>
<li><p>Prueba de matemáticas e ingles en R3</p></li>
</ul>
</section>

<section id="atrición" class="title-slide slide level1 center">
<h1>Atrición</h1>
<ul>
<li><p>¿Qué es atrición?</p></li>
<li><p>¿Qué observamos?</p></li>
<li><p>¿Cómo se obtienen los resultados de la Tabla 1</p></li>
</ul>
</section>

<section id="atrición-1" class="title-slide slide level1 center">
<h1>Atrición</h1>
<div class="cell" data-warnings="false">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:80%; ">
<table class="lightable-paper lightable-hover caption-top" data-quarto-postprocess="true" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;border-bottom: 0;">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Análisis de atrición
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Variable dependiente:
</div></th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(1)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(2)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(3)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Entrevistado en ronda 3</td>
<td style="text-align: center;">Entrevistado en las tres rondas</td>
<td style="text-align: center;">Tomó prueba de educación</td>
</tr>
<tr class="even">
<td style="text-align: left;">Condicional</td>
<td style="text-align: center;">0.020</td>
<td style="text-align: center;">0.021</td>
<td style="text-align: center;">0.029 *</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.015)</td>
<td style="text-align: center;">(0.030)</td>
<td style="text-align: center;">(0.016)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Incondicional</td>
<td style="text-align: center;">0.021</td>
<td style="text-align: center;">0.030</td>
<td style="text-align: center;">0.035 *</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.019)</td>
<td style="text-align: center;">(0.024)</td>
<td style="text-align: center;">(0.020)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Media en grupo de control</td>
<td style="text-align: center;">0.946</td>
<td style="text-align: center;">0.893</td>
<td style="text-align: center;">0.929</td>
</tr>
<tr class="odd">
<td style="text-align: left;">\(P&gt;F(Cond.=Incond.)\)</td>
<td style="text-align: center;">0.965</td>
<td style="text-align: center;">0.797</td>
<td style="text-align: center;">0.801</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Nota:</span> <sup></sup> Adaptado de la tabla 1 de Baird, McIntosh &amp; Ozler (2011). Errores agrupados a nivel EA. La muestra se restringe a individuos que estuvieron en la escuela en la línea base y que fueron seleccionados para estar en uno de los dos grupos de tratamiento o en el grupo de control. Parámetros estimados son distintos de 0 al 99`\%` (***), 95`\%` (**) y 90`\%` (*) de confianza.</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</section>

<section id="atrición-2" class="title-slide slide level1 center">
<h1>Atrición</h1>
<ul>
<li>Estimamos la siguiente ecuación por MCO:</li>
</ul>
<p><span class="math display">\[y_i=\alpha+\beta_C C_i+\beta_U U_i + e_i\]</span></p>
<p>donde <span class="math inline">\(y_i\)</span> toma el valor de 1 si la observación estaba en la línea base y también en la R3, por ejemplo</p>
<div class="fragment">
<ul>
<li><p>¿Cómo determinamos que hay diferencias significativas?</p></li>
<li><p>Por ejemplo, ¿qué significa el <span class="math inline">\(0.29^*\)</span> (error estándar de 0.016) en la primera fila de la columna (3)?</p></li>
</ul>
</div>
</section>

<section id="pruebas-de-balance" class="title-slide slide level1 center">
<h1>Pruebas de balance</h1>
<ul>
<li><p>Un aspecto que siempre revisamos cuando leemos resultados experimentales</p></li>
<li><p>Verificamos que las características observables antes de la implementación de la intervención sean iguales (en un sentido estadístico) entre los individuos asignados a los distintos grupos</p></li>
<li><p>¿Qué observamos en la tabla 2?</p></li>
</ul>
</section>

<section id="pruebas-de-balance-1" class="title-slide slide level1 center">
<h1>Pruebas de balance</h1>
<div class="cell" data-warnings="false">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:80%; ">
<table class="lightable-paper lightable-hover caption-top" data-quarto-postprocess="true" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;border-bottom: 0;">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Balance de características individuales
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Medias
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; empty-cells: hide; position: sticky; top: 0; background-color: #FFFFFF;"></th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(1)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(2)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(3)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(4)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Control</td>
<td style="text-align: center;">Condicional</td>
<td style="text-align: center;">Incondicional</td>
<td style="text-align: center;">Valor \(p\) (Cond. - Incond.)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Edad</td>
<td style="text-align: center;">15.252</td>
<td style="text-align: center;">14.952*</td>
<td style="text-align: center;">15.424</td>
<td style="text-align: center;">0.007***</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">(1.903)</td>
<td style="text-align: center;">(1.827)</td>
<td style="text-align: center;">(1.923)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Grado máximo</td>
<td style="text-align: center;">7.478</td>
<td style="text-align: center;">7.246</td>
<td style="text-align: center;">7.896**</td>
<td style="text-align: center;">0.004***</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">(1.634)</td>
<td style="text-align: center;">(1.598)</td>
<td style="text-align: center;">(1.604)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Madre vive</td>
<td style="text-align: center;">0.842</td>
<td style="text-align: center;">0.802</td>
<td style="text-align: center;">0.836</td>
<td style="text-align: center;">0.360</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.365)</td>
<td style="text-align: center;">(0.399)</td>
<td style="text-align: center;">(0.371)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Padre vive</td>
<td style="text-align: center;">0.705</td>
<td style="text-align: center;">0.714</td>
<td style="text-align: center;">0.759</td>
<td style="text-align: center;">0.288</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.456)</td>
<td style="text-align: center;">(0.453)</td>
<td style="text-align: center;">(0.428)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Nunca tuvo sexo</td>
<td style="text-align: center;">0.797</td>
<td style="text-align: center;">0.797</td>
<td style="text-align: center;">0.775</td>
<td style="text-align: center;">0.582</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.402)</td>
<td style="text-align: center;">(0.403)</td>
<td style="text-align: center;">(0.419)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Embarazada alguna vez</td>
<td style="text-align: center;">0.023</td>
<td style="text-align: center;">0.030</td>
<td style="text-align: center;">0.031</td>
<td style="text-align: center;">0.973</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.149)</td>
<td style="text-align: center;">(0.171)</td>
<td style="text-align: center;">(0.173)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Transferencia</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;">3.090</td>
<td style="text-align: center;">3.033</td>
<td style="text-align: center;">0.606</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(1.431)</td>
<td style="text-align: center;">(1.451)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">N</td>
<td style="text-align: center;">1,356</td>
<td style="text-align: center;">470</td>
<td style="text-align: center;">261</td>
<td style="text-align: center;"></td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Nota:</span> <sup></sup> Adaptado de la tabla 2, panel B, de Baird, McIntosh &amp; Ozler (2011). Errores agrupados a nivel EA. Diferencias de medias distintas de 0 al 99`\%` (***), 95`\%` (**) y 90`\%` (*) de confianza. Los asteriscos en las columnas (2) y (3) indican diferencias significativas con respecto a grupo de control. Los asteriscos en la columna (4) indican diferencias entre los grupos con tratamiento condicional e incondicional.</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</section>

<section id="pruebas-de-balance-2" class="title-slide slide level1 center">
<h1>Pruebas de balance</h1>
<ul>
<li><p>¿Cómo obtenemos estos resultados en la práctica?</p></li>
<li><p>En este artículo, se calculan las medias de cada característica en cada grupo (control, tratamiento condicional y tratamiento incondicional) y se hace una prueba de diferencia de medias</p></li>
<li><p>Juzgamos la significancia estadística de la diferencia de medias</p></li>
</ul>
</section>

<section id="pruebas-de-balance-3" class="title-slide slide level1 center">
<h1>Pruebas de balance</h1>
<ul>
<li><p>Por ejemplo, para el grado máximo, la media en el grupo de control es 7.478 y en el tratamiento condicional es de 7.246, una diferencia de 0.232</p></li>
<li><p>¿Es esta diferencia una diferencia que surge solo por cuestiones del muestreo (<em>by chance</em>)?</p></li>
<li><p>Abordaremos con detalle el asunto de la significancia estadística</p></li>
<li><p>Por ahora, podemos decir que indicamos con <span class="math inline">\(^*\)</span> una diferencia que es distinta de 0 con un 90% de confianza</p></li>
<li><p>Es decir, si tuviéramos acceso a muestras repetidas, existe 10% de probabilidad de rechazar la hipótesis de que las medias son iguales cuando no deberíamos hacerlo</p></li>
<li><p>De manera similar, <span class="math inline">\(^{***}\)</span> significa que dicha probabilidad es de 1%</p></li>
</ul>
</section>

<section id="pruebas-de-balance-4" class="title-slide slide level1 center">
<h1>Pruebas de balance</h1>
<ul>
<li>Otra forma de realizar las pruebas de balance sería como sigue:</li>
</ul>
<p><span class="math display">\[x_i=\alpha+\beta_C C_i+\beta_U U_i+u_i\]</span></p>
<ul>
<li><p>Aquí la interpretación es con respecto a <span class="math inline">\(\beta_C\)</span> y <span class="math inline">\(\beta_U\)</span></p></li>
<li><p>Nuestra hipótesis es que la variable <span class="math inline">\(x_i\)</span> no es en promedio distinta entre los distintos grupos de tratamiento y control</p></li>
<li><p>En otras palabras, se juzga la significancia estadística de <span class="math inline">\(\beta_C\)</span> y <span class="math inline">\(\beta_U\)</span></p></li>
</ul>
</section>

<section id="efectos-de-tratamiento" class="title-slide slide level1 center">
<h1>Efectos de tratamiento</h1>
<ul>
<li>Efectos en la asistencia usando las listas</li>
</ul>
<div class="cell" data-warnings="false">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:70%; ">
<table class="lightable-paper lightable-hover caption-top" data-quarto-postprocess="true" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;border-bottom: 0;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th colspan="6" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Impactos del programa en la asistencia
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Variable dependiente: fracción de los días que el entrevistado asistió a la escuela
</div></th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(1)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(2)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(3)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(4)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(5)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Primer periodo 2009</td>
<td style="text-align: center;">Segundo periodo 2009</td>
<td style="text-align: center;">Tercer periodo 2009</td>
<td style="text-align: center;">Todo 2009</td>
<td style="text-align: center;">Primer periodo 2010</td>
</tr>
<tr class="even">
<td style="text-align: left;">Condicional</td>
<td style="text-align: center;">0.139***</td>
<td style="text-align: center;">0.014</td>
<td style="text-align: center;">0.169**</td>
<td style="text-align: center;">0.080**</td>
<td style="text-align: center;">0.092**</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.045)</td>
<td style="text-align: center;">(0.033)</td>
<td style="text-align: center;">(0.085)</td>
<td style="text-align: center;">(0.035)</td>
<td style="text-align: center;">(0.041)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Incondicional</td>
<td style="text-align: center;">0.063</td>
<td style="text-align: center;">0.038</td>
<td style="text-align: center;">0.118</td>
<td style="text-align: center;">0.058</td>
<td style="text-align: center;">-0.038</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.056)</td>
<td style="text-align: center;">(0.033)</td>
<td style="text-align: center;">(0.102)</td>
<td style="text-align: center;">(0.037)</td>
<td style="text-align: center;">(0.053)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Media en control</td>
<td style="text-align: center;">0.778</td>
<td style="text-align: center;">0.849</td>
<td style="text-align: center;">0.688</td>
<td style="text-align: center;">0.810</td>
<td style="text-align: center;">0.801</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N</td>
<td style="text-align: center;">284</td>
<td style="text-align: center;">285</td>
<td style="text-align: center;">192</td>
<td style="text-align: center;">319</td>
<td style="text-align: center;">211</td>
</tr>
<tr class="even">
<td style="text-align: left;">\(P&gt;F(Cond.=Incond.\)</td>
<td style="text-align: center;">0.129</td>
<td style="text-align: center;">0.334</td>
<td style="text-align: center;">0.358</td>
<td style="text-align: center;">0.436</td>
<td style="text-align: center;">0.010</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Nota:</span> <sup></sup> Adaptado de la tabla 5 de Baird, McIntosh &amp; Ozler (2011). Errores agrupados a nivel EA. Se incluyen como controles indicadoras de edad, indicadoras de estrato, el índice de activos del hogar, el grado máximo de estudios y una indicadora de nunca haber tenido sexo. Parámetros estimados estadísticamente distintos de 0 al 99`\%` (***), 95`\%` (**) y 90`\%` (*) de confianza.</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</section>

<section id="efectos-de-tratamiento-1" class="title-slide slide level1 center">
<h1>Efectos de tratamiento</h1>
<ul>
<li>¿Cómo obtenemos los efectos de tratamiento?</li>
</ul>
<p><span class="math display">\[y_i=\alpha+\beta_C C_i+\beta_U U_i +X_i'\gamma+u_i\]</span></p>
<ul>
<li><p><span class="math inline">\(X_i\)</span> son las características en la línea base</p></li>
<li><p>Como el tratamiento se asignó de manera aleatoria, esperamos que <span class="math inline">\(X_i\)</span> no esté correlacionado con el error, pero que sí mejore la precisión de los estimadores</p></li>
</ul>
<div class="fragment">
<ul>
<li><p>Otros aspectos técnicos que iremos cubriendo:</p>
<ul>
<li><p>Errores estándar agrupados a nivel EA</p></li>
<li><p>Indicadores de estrato de aleatorización (ciudad, semiurbano, rural)</p></li>
</ul></li>
</ul>
</div>
</section>

<section id="efectos-en-pruebas-académicas" class="title-slide slide level1 center">
<h1>Efectos en pruebas académicas</h1>
<ul>
<li><p>Muchas veces se emplean <em>z-scores</em></p></li>
<li><p>Supongamos que en un test los alumnos tienen una calificación <span class="math inline">\(y_i\)</span></p></li>
<li><p>Definimos <span class="math inline">\(z_i=\frac{y_i-\bar{y}}{de(y)}\)</span></p></li>
<li><p>Tiene la ventaja de interpretación: <span class="math inline">\(\beta\)</span> es el cambio en desviaciones estándar</p></li>
</ul>
</section>

<section id="efectos-en-matrimonios-y-embarazos" class="title-slide slide level1 center">
<h1>Efectos en matrimonios y embarazos</h1>
<ul>
<li><p>Efectos grandes en UCT, pero no hay efectos de CCT</p></li>
<li><p>Parece en contra de lo que hubiéramos esperado</p></li>
<li><p>Interpretación basada en <em>cumplidores</em> y <em>no cumplidores</em>, lo cual veremos más adelante en el curso</p></li>
</ul>
</section>

<section id="próxima-sesión" class="title-slide slide level1 center">
<h1>Próxima sesión</h1>
<ul>
<li><p>Hablaré sobre las medidas de variabilidad para realizar inferencia</p>
<ul>
<li>MM, Capítulo 1, Apéndice</li>
</ul></li>
<li><p>Haré un recordatorio de MCO y sus propiedades asintóticas</p></li>
</ul>
</section>

<section id="section" class="title-slide slide level1 inverse center middle">
<h1></h1>
<p>Presentación creada usando el paquete <a href="https://github.com/yihui/xaringan"><strong>xaringan</strong></a> en R.</p>
<p>El <em>chakra</em> viene de <a href="https://remarkjs.com">remark.js</a>, <a href="http://yihui.org/knitr"><strong>knitr</strong></a>, y <a href="https://rmarkdown.rstudio.com">R Markdown</a>.</p>
<p>Material de clase en versión preliminar.</p>
<p><strong>No reproducir, no distribuir, no citar.</strong></p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/122010/logo_cide_verde.png?itok=NUstTkpt" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>