<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-contrib/bootstrap-icons-1.13.1/bootstrap-icons.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <title>Inferencia Causal 2025 – late</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-31fd4380ed2edc88e26f7c115086bfb8.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>

  <link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section id="late-y-variables-instrumentales" class="title-slide slide level1 portada center">
<h1>LATE y variables instrumentales</h1>
<div style="text-align: center; font-size: 1.2em; font-weight: bold;">
<p>Inferencia Causal</p>
</div>
<div style="text-align: center; margin-top: 1em;">
<p><strong>Irvin Rojas</strong><br>
<br> <a href="https://rojasirvin.com" style="color: #ffffff;">rojasirvin.com</a></p>
</div>
<div style="text-align: center; margin-top: 1em;">
<p><a href="https://github.com/rojasirvin" target="_blank" style="margin-right: 0 10px;"></a></p><a href="https://github.com/rojasirvin" target="_blank" style="margin-right: 0 10px;">
<pre><code></code></pre>
</a><p><a href="https://github.com/rojasirvin" target="_blank" style="margin-right: 0 10px;"></a> <a href="https://twitter.com/RojasIrvin" target="_blank" style="margin-right: 0 10px;"></a></p><a href="https://twitter.com/RojasIrvin" target="_blank" style="margin-right: 0 10px;">
<pre><code></code></pre>
</a><p><a href="https://twitter.com/RojasIrvin" target="_blank" style="margin-right: 0 10px;"></a> <a href="https://scholar.google.com/citations?user=FUwdSTMAAAAJ&amp;hl=en" style="margin: 0 10px;"></a></p><a href="https://scholar.google.com/citations?user=FUwdSTMAAAAJ&amp;hl=en" style="margin: 0 10px;">
<pre><code></code></pre>
</a><p><a href="https://scholar.google.com/citations?user=FUwdSTMAAAAJ&amp;hl=en" style="margin: 0 10px;"></a></p>
</div>
</section>

<section>
<section id="cumplimiento-no-perfecto" class="title-slide slide level1 inverse center middle">
<h1>Cumplimiento no perfecto</h1>

</section>
<section id="fracasó-el-experimento" class="slide level2">
<h2>¿Fracasó el experimento?</h2>
<ul>
<li><p>Frecuentemente nos encontraremos con intervenciones donde la aleatorización ocurre de manera íntegra, pero no todos aquellos asignados a cierto tratamiento efectivamente lo reciben</p></li>
<li><p>Nos tomaremos en serio la diferencia entre <strong>ser asignado</strong> al tratamiento y <strong>recibir el tratamiento</strong></p>
<ul>
<li>Al evaluar un programa que asigna aleatoriamente a niños a escuelas de prestigio, nos interesa el efecto de efectivamente asistir a dichas escuelas y, quizás no tanto, el efecto de haber sido sorteado para asistir a dichas escuelas</li>
</ul></li>
</ul>
</section>
<section id="fracasó-el-experimento-1" class="slide level2">
<h2>¿Fracasó el experimento?</h2>
<ul>
<li><p>Usaremos un estimador de variables instrumentales (VI) para relacionar los efectos de la <strong>asignación</strong> con los efectos de la <strong>adopción</strong></p></li>
<li><p>Llegaremos al siguiente resultado:</p></li>
</ul>
<p><span class="math display">\[\text{Efecto de la asignación en } Y=(\text{Efecto de la asignación en la adopción})\times (\text{Efecto de la adopción en }Y)\]</span></p>
<ul>
<li>Por tanto:</li>
</ul>
<p><span class="math display">\[\text{Efecto de la adopción en }Y=\frac{\text{Efecto de la asignación en }Y}{\text{Efecto de las asignación en la adopción}}\]</span></p>
<ul>
<li>Ahora derivaremos formalmente este resultado, pero la intución es importante: el efecto causal de la adopción es el efecto de la asignación, <em>escalado</em> por el efecto de la asignación en la adopción</li>
</ul>
</section></section>
<section>
<section id="efectos-causales-con-cumplimiento-imperfecto" class="title-slide slide level1 inverse center middle">
<h1>Efectos causales con cumplimiento imperfecto</h1>

</section>
<section id="identificación-de-efectos-causales-usando-vi" class="slide level2">
<h2>Identificación de efectos causales usando VI</h2>
<ul>
<li><p>Angrist, Imbens &amp; Rubin (1996)</p></li>
<li><p>Asignación: <span class="math inline">\(Z_i=\begin{cases} 1 \\0 \\ \end{cases}\)</span></p></li>
<li><p>Cumplimiento: <span class="math inline">\(D_i=\begin{cases} 1 \\0 \\ \end{cases}\)</span></p></li>
<li><p><span class="math inline">\(Y_i\)</span> variable de resultados</p></li>
<li><p>Nos importa el efecto de <span class="math inline">\(D_i\)</span> sobre <span class="math inline">\(Y_i\)</span></p></li>
</ul>
</section>
<section id="efectos-causales-y-vi" class="slide level2">
<h2>Efectos causales y VI</h2>
<ul>
<li><p><span class="math inline">\(D_i(Z)\)</span> es el indicador de cumplir, dada la asignación <span class="math inline">\(Z\)</span></p></li>
<li><p>Con cumplimiento perfecto tendríamos <span class="math inline">\(D_i(Z)=Z_i\)</span></p></li>
<li><p>En general, hay asignados que no cumplen y no asignados que cumplen</p></li>
<li><p><span class="math inline">\(Y_i(Z,D)\)</span> es la variable de interés de <span class="math inline">\(i\)</span></p></li>
<li><p><span class="math inline">\(Y_i(Z,D)\)</span> y <span class="math inline">\(D_i(Z)\)</span> son resultados potenciales</p></li>
</ul>
</section>
<section id="supuestos" class="slide level2">
<h2>Supuestos</h2>
<p><strong>Supuesto 1</strong>: <em>Stable Unit Treatment Value Assumption (SUTVA)</em></p>
<ul>
<li><p>Este supuesto indica que los resultados potenciales de <span class="math inline">\(i\)</span> no están correlacionados con los de los otros individuos</p></li>
<li><p>Por tanto podemos escribir <span class="math inline">\(Y_i(Z,D)=Y_i(Z_i,D_i)\)</span> y <span class="math inline">\(D_i(Z)=D_i(Z_i)\)</span></p></li>
</ul>
<p><strong>Supuesto 2</strong>: asignación aleatoria</p>
<ul>
<li>La asignación de <span class="math inline">\(Z_i\)</span> es aleatoria, es decir, <span class="math inline">\(P(Z=C)=P(Z=C')\)</span> para todo <span class="math inline">\(C\)</span> y <span class="math inline">\(C'\)</span></li>
</ul>
<div class="fragment">
<ul>
<li>Los supuestos 1 y 2 nos permiten identificar los efectos causales de <span class="math inline">\(Z\)</span> en <span class="math inline">\(Y\)</span> y de <span class="math inline">\(Z\)</span> en <span class="math inline">\(D\)</span> calculando diferencias de medias por grupos de <span class="math inline">\(Z\)</span>:
<ul>
<li><span class="math inline">\(ITT_Y\)</span> comparar las medias de <span class="math inline">\(y\)</span> entre quienes <span class="math inline">\(Z=1\)</span> y quienes <span class="math inline">\(Z=0\)</span></li>
<li><span class="math inline">\(ITT_D\)</span> comparar las medias de <span class="math inline">\(D\)</span> entre quienes <span class="math inline">\(Z=1\)</span> y quienes <span class="math inline">\(Z=0\)</span></li>
</ul></li>
<li><span class="math inline">\(ITT\)</span> se conoce como <strong>intención a tratar</strong> o <strong>intention to treat</strong></li>
</ul>
</div>
</section>
<section id="parada-para-reflexionar" class="slide level2">
<h2>Parada para reflexionar</h2>
<ul>
<li><p>Hasta ahora el supuesto crítico es la asignación aleatoria de <span class="math inline">\(Z\)</span></p></li>
<li><p><span class="math inline">\(D_i\)</span> puede no serlo y, en general, no lo es</p></li>
<li><p>Por tanto, una comparación de <span class="math inline">\(y\)</span> entre grupos de <span class="math inline">\(D\)</span> es inapropiada</p></li>
<li><p>Necesitamos algunos supuestos para decir algo del efecto causal de <span class="math inline">\(D\)</span> sobre <span class="math inline">\(Y\)</span></p></li>
</ul>
</section>
<section id="más-supuestos" class="slide level2">
<h2>Más supuestos</h2>
<p><strong>Supuesto 3</strong>: restricción de exclusión</p>
<p><span class="math display">\[Y(Z,D)=Y(Z',D)\quad \forall \quad Z,Z',D\]</span></p>
<ul>
<li>Este supuesto implica que podemos escribir:</li>
</ul>
<p><span class="math display">\[Y_i(1,d)=Y_i(0,d) \quad d=\{0,1\}\]</span></p>
<ul>
<li>Es decir, resuleve el problema contrafactual</li>
</ul>
<div class="fragment">
<ul>
<li>Con el supuesto 3 podemos escribir: <span class="math display">\[Y(D)=Y(Z,D)=Y(Z',D)\quad \forall \quad Z,Z',D\]</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Y por el supuesto 1: <span class="math display">\[Y_i(D_i)=Y_i(Z,D)\]</span></li>
</ul>
</div>
</section>
<section id="más-supuestos-1" class="slide level2">
<h2>Más supuestos</h2>
<p><strong>Supuesto 4</strong>: el efecto causal promedio de <span class="math inline">\(Z\)</span> sobre <span class="math inline">\(D\)</span> es distinto de cero</p>
<ul>
<li><p>Esto es, <span class="math inline">\(E(D_i(1)-D_i(0))\neq0\)</span></p></li>
<li><p>En otras palabras, la asignación tiene efecto sobre el cumplimiento</p></li>
</ul>
<div class="fragment">
<p><strong>Supuesto 5</strong>: monotonicidad <span class="math display">\[D_i(1)\geq D_i(0) \quad \forall\quad i=1,\ldots N\]</span></p>
<ul>
<li><p>Este supuesto simplemente dice que no hay un individuo que:</p>
<ul>
<li>Cuando se le asigna, no cumple</li>
<li>Cuando no se le asigna, cumple</li>
</ul></li>
<li><p>Noten que este supuesto se debe pensar en términos contrafactuales</p></li>
<li><p>A un individuo que no cumple cuando se le asigna y cumple cuando no se le asigna se le conoce como <strong>retador</strong> o <em>defier</em></p></li>
</ul>
</div>
</section>
<section id="variable-instrumental" class="slide level2">
<h2>Variable instrumental</h2>
<ul>
<li><span class="math inline">\(Z\)</span> es una <strong>variable instrumental</strong> para el efecto causal de <span class="math inline">\(D\)</span> sobre <span class="math inline">\(Y\)</span> si se cumplen los supuestos 1 al 5</li>
</ul>
</section>
<section id="interpretación-del-estimador-de-vi" class="slide level2">
<h2>Interpretación del estimador de VI</h2>
<ul>
<li>Comencemos escribiendo el efecto causal de <span class="math inline">\(Z\)</span> en <span class="math inline">\(Y\)</span>, que por el supuesto de exclusión de <span class="math inline">\(Z\)</span> es:</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
Y_i(1,D_i(1))-Y_i(0,D_i(0))=\underbrace{Y_i(D_i(1))-Y_i(D_i(0))}_{A} \\
\end{aligned}
\]</span></p>
<div class="fragment">
<ul>
<li>Notemos que el lado derecho, <span class="math inline">\(A\)</span>, puede calcularse siguiendo la notación de resultados potenciales: <span class="math display">\[
\begin{aligned}
Y(D)&amp;=Y(0)+D(Z)(Y(1)-Y(0)) \\
D(Z)&amp;=D(0)+Z(D(1)-D(0))\\
\end{aligned}
\]</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Sustituyendo <span class="math inline">\(D\)</span> en <span class="math inline">\(Y\)</span>: <span class="math display">\[
\begin{aligned}
Y(D(Z))&amp;=Y(0)+(D(0)+Z(D(1)-D(0)))(Y(1)-Y(0)) \\
&amp;=Y(0)D(0)(Y(1)-Y(0))+Z(D(1)-D(0))(Y(1)-Y(0))
\end{aligned}
\]</span></li>
</ul>
</div>
</section>
<section id="interpretación-del-estimador-de-vi-1" class="slide level2">
<h2>Interpretación del estimador de VI</h2>
<ul>
<li>Podemos evaluar entonces los dos valores de <span class="math inline">\(Z\)</span> y obtener:</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
Y(D(1))&amp;=Y(0)+D(1)(Y(1)-Y(0)) \\
Y(D(0))&amp;=Y(0)+D(0)(Y(1))-Y(0) \\
\end{aligned}
\]</span></p>
<div class="fragment">
<ul>
<li>Y entonces: <span class="math display">\[
\begin{aligned}
A&amp;=Y_i(D_i(1))-Y_i(D_i(0)) \\
&amp;=(Y_i(1)-Y_i(0))(D_i(1)-D_i(0))\\
\end{aligned}
\]</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Es decir, el efecto causal de <span class="math inline">\(Z\)</span> sobre <span class="math inline">\(Y\)</span> para <span class="math inline">\(i\)</span> es el producto del efecto causal de <span class="math inline">\(D\)</span> sobre <span class="math inline">\(Y\)</span> y del efecto causal de <span class="math inline">\(Z\)</span> sobre <span class="math inline">\(D\)</span>:</li>
</ul>
<p><span class="math display">\[
\underbrace{Y_i(1,D_i(1))-Y_i(0,D_i(0))}_B=(Y_i(1)-Y_i(0))(D_i(1)-D_i(0))
\]</span></p>
</div>
</section>
<section id="interpretación-causal-del-estimador-de-vi" class="slide level2">
<h2>Interpretación causal del estimador de VI</h2>
<ul>
<li>Consideremos ahora <span class="math inline">\(B\)</span> y obtengamos el valor esperado:</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
E(Y_i(1,D_i(1))-Y_i(0,D_i(0)))&amp;=E(Y_i(1)-Y_i(0))(D_i(1)-D_i(0))\\
&amp;=E(Y_i(1)-Y_i(0)|D_i(1)-D_i(0)=1)P(D_i(1)-D_i(0)=1)\\
&amp;+E(Y_i(1)-Y_i(0)|D_i(1)-D_i(0)=0)P(D_i(1)-D_i(0)=0)\\
&amp;+E(Y_i(1)-Y_i(0)|D_i(1)-D_i(0)=-1)P(D_i(1)-D_i(0)=-1)\\
\end{aligned}
\]</span></p>
<div class="fragment">
<ul>
<li>La intuición de este valor esperado es obtener el efecto en la variable de interés bajo los distintos posibles efectos de <span class="math inline">\(Z\)</span> sobre <span class="math inline">\(D\)</span></li>
<li>El segundo término de la suma es cero y corresponde a aquellos para quienes la asignación no modificó el cumplimento, por lo que <span class="math inline">\(E(Y_i(1)-Y_i(0)|D_i(1)-D_i(0)=0)=0\)</span></li>
<li>Usando el supuesto 5 de monotonicidad, sabemos <span class="math inline">\(D_i(1)-D_i(0)\)</span> es igual a uno o cero, es decir, <span class="math inline">\(P(D_i(1)-D_i(0)=-1)=0\)</span></li>
</ul>
</div>
</section>
<section id="interpretación-causal-del-estimador-de-vi-1" class="slide level2">
<h2>Interpretación causal del estimador de VI</h2>
<ul>
<li>Por tanto:</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
E(Y_i(1,D_i(1))-Y_i(0,D_i(0)))=E(Y_i(1)-Y_i(0)|D_i(1)-D_i(0)=1)P(D_i(1)-D_i(0)=1)
\end{aligned}
\]</span></p>
<div class="fragment">
<ul>
<li>Es decir, el efecto causal promedio de <span class="math inline">\(Z\)</span> sobre <span class="math inline">\(Y\)</span> es igual al producto del efecto causal promedio de <span class="math inline">\(D\)</span> sobre <span class="math inline">\(Y\)</span> en aquellos individuos que cuando se les asigna cumplen y cuando no se les asigna no cumplen, <span class="math inline">\(D_i(0)=0\)</span> y <span class="math inline">\(D_i(1)=1\)</span>, y la proporción de estos individuos en la población</li>
</ul>
</div>
</section>
<section id="interpretación-causal-del-estimador-de-vi-2" class="slide level2">
<h2>Interpretación causal del estimador de VI</h2>
<p><strong>Proposición 1 en Angrist, Imbens &amp; Rubin (1996)</strong>: interpretación causal del estimador de VI</p>
<ul>
<li>Si los supuestos 1 a 5 se cumplen, el estimador de VI es:</li>
</ul>
<p><span class="math display">\[E(Y_i(1)-Y_i(0)|D_i(1)-D_i(0)=1)=\frac{E(Y_i(D_i(1),1))-Y_i(D_i(0),0)}{E(D_i(1)-D_i(0)}=\lambda_{LATE}\]</span></p>
<ul>
<li><p>Angrist y coautores llaman a este parámetro el <strong>efecto local promedio del tratamiento</strong> o <em>LATE</em></p></li>
<li><p>El LATE es el efecto causal promedio del tratamiento en un conjunto de individuos cuyo estatus de tratamiento puede ser modificado por la asignación aleatoria</p></li>
<li><p>A estos individuos se les conoce como <strong>cumplidores</strong> o <em>compliers</em></p></li>
</ul>
</section>
<section id="tipos-de-individuos" class="slide level2 scroll-diapo">
<h2>Tipos de individuos</h2>
<ul>
<li>Hay cuatro tipos de individuos:</li>
</ul>
<div class="cell" data-warnings="false">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:40%; ">
<table class="lightable-paper lightable-hover caption-top" data-quarto-postprocess="true" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;border-bottom: 0;">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Tipos de individuos
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">\(D_i(0)=0\)</td>
<td style="text-align: center;">\(D_i(0)=1\)</td>
</tr>
<tr class="even">
<td style="text-align: left;">\(D_i(1)=0\)</td>
<td style="text-align: center;">\(Y_i(1,0)-Y_i(0,0)=0\)</td>
<td style="text-align: center;">\(Y_i(1,0)-Y_i(0,1)=-(Y_i(1)-Y_i(0))\)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Nunca cumplidor</td>
<td style="text-align: center;">Retador</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">\(D_i(1)=1\)</td>
<td style="text-align: center;">\(Y_i(1,1)-Y_i(0,0)=Y_i(1)-Y_i(0)\)</td>
<td style="text-align: center;">\(Y_i(1,1)-Y_i(0,1)=0\)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Cumplidor</td>
<td style="text-align: center;">Siempre adoptador</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Nota:</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Adaptado de la tabla 1 en Angrist, Imbens &amp; Rubin (1996).</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>

</div>
</section>
<section id="tipos-de-individuos-1" class="slide level2">
<h2>Tipos de individuos</h2>
<ul>
<li><p>Los cumplidores cumplen con el tratamiento si se les asigna y no lo cumplen si no se les asigna</p></li>
<li><p><span class="math inline">\(Z\)</span> es independiente de <span class="math inline">\(D\)</span> para los nunca cumplidores y los siempre adoptadores y el efecto causal es 0 para ambos</p></li>
<li><p>Los retadores hacen lo contrario a lo que les es asignado</p>
<ul>
<li>El supuesto de monotonicidad descarta la existencia de retadores para la identificación del LATE</li>
<li>En la práctica, esperamos que sean pocos tal que podamos ignorarlos</li>
</ul></li>
<li><p>A la suma de nunca cumplidores, siempre adoptadores y retadores se le conoce como <strong>no cumplidores</strong></p></li>
</ul>
</section>
<section id="late-y-tt" class="slide level2">
<h2>LATE y TT</h2>
<ul>
<li><p>En general el LATE y el TT (TOT o ATET) difieren</p></li>
<li><p>Pero recordemos que <span class="math inline">\(TT=E(y_{1i}-y_{0i}|D_i=1)\)</span></p></li>
<li><p>Noten que en el conjunto con <span class="math inline">\(D_i=1\)</span> se encuentran los cumplidores y los siempre adoptadores</p></li>
<li><p>Si podemos asegurar que no hay siempre adoptadores, el LATE y el TT son iguales</p></li>
</ul>
</section>
<section id="resumiendo" class="slide level2">
<h2>Resumiendo</h2>
<ul>
<li><p>Hemos mostrado que el efecto promedio de <span class="math inline">\(Z\)</span> sobre <span class="math inline">\(Y\)</span> es proporcional al efecto de <span class="math inline">\(D\)</span> sobre <span class="math inline">\(Y\)</span> para los cumplidores</p></li>
<li><p>Por el supuesto 4, sabemos que la proporción de cumplidores es igual al efecto de <span class="math inline">\(Z\)</span> sobre <span class="math inline">\(D\)</span></p></li>
<li><p>Dado que <span class="math inline">\(Z\)</span> se asigna aleatoriamente, podemos estimar los dos ITT por separado para obtener <span class="math inline">\(\lambda=\frac{ITT_Y}{ITT_D}\)</span></p></li>
</ul>
<div class="fragment">
<ul>
<li>En la práctica de evaluación recurrimos a la econometría con variables instrumentales</li>
</ul>
</div>
</section></section>
<section>
<section id="variables-instrumentales-y-late" class="title-slide slide level1 inverse center middle">
<h1>Variables instrumentales y LATE</h1>

</section>
<section id="terminología" class="slide level2">
<h2>Terminología</h2>
<ul>
<li><strong>Primera etapa</strong>: es el efecto causal de la asignación sobre el cumplimento</li>
</ul>
<p><span class="math display">\[\phi=E(D_i|Z_i=1)-E(D_i|Z_i=0)\]</span></p>
<ul>
<li><strong>Forma reducida</strong>: es la diferencia en <span class="math inline">\(y\)</span> entre grupos de asignación</li>
</ul>
<p><span class="math display">\[\rho=E(y_i|Z_i=1)-E(y_i|Z_i=0)\]</span></p>
<ul>
<li><strong>LATE</strong>: es la diferencia en <span class="math inline">\(y\)</span> entre a quienes se les asigna el tratamiento y quienes no, dividida por la diferencia en cumplimiento entre a quienes se les asigna el tratamiento y quienes no</li>
</ul>
<p><span class="math display">\[\lambda_{LATE}=\frac{\rho}{\phi}\]</span></p>
</section>
<section id="variables-instrumentales-en-investigación-criminológica" class="slide level2">
<h2>Variables instrumentales en investigación criminológica</h2>
<ul>
<li><p>Angrist (2006) estudia un experimento bastante particular: aleatorizar la respuesta policíaca</p></li>
<li><p>¿En qué consistió la intervención?</p></li>
</ul>
<div class="fragment">
<ul>
<li><span class="math inline">\(y_i\)</span>: tasa de reincidencia en conductas de violencia doméstica</li>
<li><span class="math inline">\(Z_i=\begin{cases} 1\quad \text{si apercibido} \\ 0\quad \text{otro caso}\ \end{cases}\)</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Se muestra como el ITT puede no reflejar la efectividad de la intervención debido al efecto de <em>dilusión</em> provocado, en este caso, por desviaciones con respecto a la forma de enfrentar un episodio policíaco</li>
</ul>
</div>
</section>
<section id="diferencias-en-las-respuestas-efectivas" class="slide level2">
<h2>Diferencias en las respuestas efectivas</h2>
<div class="cell" data-warnings="false">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:60%; ">
<table class="lightable-paper lightable-hover caption-top" data-quarto-postprocess="true" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;border-bottom: 0;">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Tratamiento asignado y recibido en casos de violencia doméstica
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Tramiento recibido:
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; empty-cells: hide; position: sticky; top: 0; background-color: #FFFFFF;"></th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Arrestado</td>
<td style="text-align: center;">Apercibido</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Tratamiento asignado:</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">Total</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arrestar</td>
<td style="text-align: center;">98.91 (91)</td>
<td style="text-align: center;">1.09 (1)</td>
<td style="text-align: center;">29.3 (92)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Apercibir</td>
<td style="text-align: center;">20.27 (45)</td>
<td style="text-align: center;">79.73 (177)</td>
<td style="text-align: center;">70.7 (222)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;">43.1 (136)</td>
<td style="text-align: center;">56.69 (178)</td>
<td style="text-align: center;">100 (314)</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Nota:</span> <sup></sup> Adaptado de la tabla 1 en Angrist (2006).</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>

</div>
<ul>
<li><p>En el estudio original, lo que llamamos <em>apercibir</em> tuvo en realidad dos componentes: <em>aconsejar</em> y <em>separar</em>, pero para facilitar el análisis usaremos solo <em>arrestar</em> por un lado y <em>apercibir</em> por el otro</p></li>
<li><p>¿Qué observamos sobre a las desviaciones con respecto al tratamiento asignado?</p></li>
</ul>
</section>
<section id="diferencias-en-las-respuestas-efectivas-1" class="slide level2">
<h2>Diferencias en las respuestas efectivas</h2>
<ul>
<li><p>Noten que cuando el tratamiento asignado era arrestar, efectivamente se arrestó al 98.91% de los individuos</p></li>
<li><p>En cambio, noten que 20.27 % de los 222 asignados a ser apercibidos fueron en efecto arrestados</p></li>
<li><p>¿Cómo ocurre el sesgo de selección en este caso?</p></li>
</ul>
</section>
<section id="sesgo-de-selección" class="slide level2">
<h2>Sesgo de selección</h2>
<ul>
<li><p>Algunos individuos se comportaron violentos, por lo que fueron arrestados a pesar de ser asignados a apercibimiento</p></li>
<li><p>Por tanto, si comparamos <span class="math inline">\(y\)</span> entre aquellos individuos apercibidos y no apercibidos, no tomamos en cuenta que aquellos no apercibidos (por tanto, arrestados) pudieran ser más violentos, sobrestimando el efecto de la política de apercibimiento</p></li>
</ul>
</section>
<section id="late" class="slide level2">
<h2>LATE</h2>
<ul>
<li><p>La primera etapa es el efecto causal en la probabilidad de recibir el tratamiento de apercibimiento por el hecho de haber sido asignado a ese tratamiento: <span class="math inline">\(E(D_i|Z_i=1)-E(D_i|Z_i=0)=0.797-0.011=0.786\)</span></p></li>
<li><p>La forma reducida es el efecto causal de la asignación al tratamiento sobre la tasa de reincidencia: <span class="math inline">\(E(y_i|Z_i=1)-E(y_i|Z_i=0)=0.211-0.097=0.114\)</span></p></li>
</ul>
<div class="fragment">
<ul>
<li>El ITT ignora el hecho de que algunos asignados a apercibimiento fueron arrestados</li>
<li>Sabemos que el LATE está dado por <span class="math inline">\(\lambda_{LATE}=\frac{ITT_y}{ITT_D}=\frac{0.114}{0.786}=0.145\)</span></li>
<li>Los datos de los autores reportan que si nos fijáramos solo en las diferencias por tipo de tratamiento obtendríamos, <span class="math inline">\(E(y_i|D_i=1)-E(y_i|D_i=0)=0.216-0.129=0.087\)</span>, es decir, casi la mitad del LATE</li>
<li>Pero como <span class="math inline">\(D\)</span> no es aleatoria, dicha comparación no es correcta</li>
</ul>
</div>
</section></section>
<section>
<section id="la-econometría-del-late" class="title-slide slide level1 inverse center middle">
<h1>La econometría del LATE</h1>

</section>
<section id="motivación-con-un-estadístico-de-wald" class="slide level2">
<h2>Motivación con un estadístico de Wald</h2>
<ul>
<li><p>Pensemos en un modelo con efectos constantes de tratamiento: <span class="math inline">\(y_{1i}-y_{0i}=\lambda\)</span></p></li>
<li><p>La variable de resultados está determinada por <span class="math inline">\(y_{0i}=\alpha+\varepsilon_i\)</span>, donde <span class="math inline">\(\alpha=E(y_{0i})\)</span></p></li>
<li><p>Entonces, el modelo de resultados potenciales es:</p></li>
</ul>
<p><span class="math display">\[y_i=\alpha+\lambda D_i+\varepsilon_i\]</span></p>
<ul>
<li>Si <span class="math inline">\(D_i\)</span> no es independiente de <span class="math inline">\(y_{0i}\)</span>, es decir, <span class="math inline">\(y_{0i}\)</span> no es independiente del error, entonces una diferencia de medias entre grupos de <span class="math inline">\(D\)</span> no produce un estimador consistente de <span class="math inline">\(\lambda\)</span></li>
</ul>
</section>
<section id="motivación-con-un-estadístico-de-wald-1" class="slide level2">
<h2>Motivación con un estadístico de Wald</h2>
<ul>
<li>Ahora supongamos que tenemos un <strong>instrumento</strong> <span class="math inline">\(z_i\)</span> tal que <span class="math inline">\(z_i\perp y_i\)</span>, es decir, <span class="math inline">\(E(\varepsilon_i|z_i)=0\)</span></li>
</ul>
<div class="fragment">
<ul>
<li>Evaluemos la esperanza de <span class="math inline">\(y_i\)</span> cuando <span class="math inline">\(z_i=1\)</span> y cuando <span class="math inline">\(z_i=0\)</span>: <span class="math display">\[
\begin{aligned}
E(y_i|z_i=1)&amp;=\alpha+\lambda E(D_i| z_i=1) \\
E(y_i|z_i=0)&amp;=\alpha+\lambda E(D_i| z_i=0) \\
\end{aligned}
\]</span></li>
<li>Restando: <span class="math display">\[E(y_i|z_i=1)-E(y_i|z_i=0)=\lambda(E(D_i| z_i=1)-E(D_i| z_i=0))\]</span></li>
<li>Y despejando obtenemos <span class="math display">\[\lambda=\frac{E(y_i|z_i=1)-E(y_i|z_i=0)}{E(D_i| z_i=1)-E(D_i| z_i=0)}\]</span> que es conocido como un <em>estadístico de Wald</em></li>
</ul>
</div>
</section>
<section id="mínimos-cuadrados-en-dos-etapas-mc2e" class="slide level2">
<h2>Mínimos cuadrados en dos etapas (MC2E)</h2>
<ul>
<li><p>En la práctica, podemos plantear un modelo econométrico en dos etapas:</p></li>
<li><p><strong>Modelo estructural</strong></p></li>
</ul>
<p><span class="math display">\[y_i=X_i'\beta+\lambda D_i+\varepsilon_i\]</span></p>
<div class="fragment">
<ul>
<li><strong>Primera etapa</strong></li>
</ul>
<p><span class="math display">\[D_i=X_i'\phi_0+\phi_1z_i+\eta_i\]</span> donde <span class="math inline">\(\phi_i\)</span> es el efecto causal de la asignación sobre el cumplimiento - Cuado <span class="math inline">\(D_i\)</span> y <span class="math inline">\(z_i\)</span> son ambas dicotómicas, <span class="math inline">\(\phi_1\)</span> da la proporción de la población que son cumplidores</p>
</div>
</section>
<section id="mínimos-cuadrados-en-dos-etapas-mc2e-1" class="slide level2">
<h2>Mínimos cuadrados en dos etapas (MC2E)</h2>
<ul>
<li>Podemos concebir el problema como uno en el que primero se estima la primera etapa y se sustituyen los valores ajustados de <span class="math inline">\(D_i\)</span> en el modelo estructural</li>
<li>Sustituyendo la primera etapa en el modelo estructural <span class="math display">\[y_i=X_i'\beta+\lambda \hat{D}_i+\varepsilon_i\]</span></li>
</ul>
<div class="fragment">
<ul>
<li>Esta es la forma de pensar el procedimiento, pero en la práctica nunca hacemos esto manualmente
<ul>
<li>Noten que <span class="math inline">\(\hat{D}_i\)</span> es estimada, por lo cual se ignora la variabilidad muestral de la primera etapa y los errores estándar serían inconsistentes</li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Nota: el estimador de Wald es igual al estimador de MC2E cuando no hay <span class="math inline">\(X\)</span> y cuando <span class="math inline">\(Z\)</span> y <span class="math inline">\(D\)</span> son binarias</li>
</ul>
</div>
</section>
<section id="mínimos-cuadrados-en-dos-etapas-mc2e-2" class="slide level2">
<h2>Mínimos cuadrados en dos etapas (MC2E)</h2>
<ul>
<li><strong>Forma reducida</strong></li>
</ul>
<p><span class="math display">\[
\begin{aligned}
y_i&amp;=X_i'\beta+\lambda(X_i'\phi_0+\phi_1z_1+\eta_i)+\varepsilon_i \\
&amp;=X_i'\rho_0+\rho_1z_i+\nu_i
\end{aligned}
\]</span> donde <span class="math inline">\(\rho_1=\lambda\phi_1\)</span> es el coeficiente de forma reducida sobre la variable de asignación</p>
<div class="fragment">
<ul>
<li>Noten que esto implica que <span class="math inline">\(\lambda=\rho_1/\phi_1\)</span></li>
<li>Es decir, <span class="math inline">\(\lambda_{MC2E}\)</span> puede interpretarse como la versión reescalada del coeficiente de forma reducida usando el efecto causal de la primera etapa para reescalar</li>
</ul>
</div>
</section>
<section id="efectos-estimados" class="slide level2">
<h2>Efectos estimados</h2>
<ul>
<li>Regresando a los resultados del experimento, ahora con econometría</li>
</ul>
<p><strong>Primera etapa</strong></p>
<ul>
<li>Versión corta:</li>
</ul>
<p><span class="math display">\[apercibido_i=\phi_0+\phi_1T_i+\eta_i\]</span></p>
<ul>
<li>Con controles: <span class="math display">\[apercibido_i=\phi_0+\phi_1T_i+X_i'\Phi +\eta_i\]</span></li>
<li>Noten que el 0.786 es exactamente lo que se encontraba al hacer las diferencias de medias</li>
</ul>
<p><strong>Forma reducida</strong></p>
<ul>
<li>También conocido como ITT</li>
</ul>
<p><span class="math display">\[reincidencia_i=\rho_0+\rho_1T_i+\nu_i\]</span></p>
</section>
<section id="efectos-estimados-1" class="slide level2">
<h2>Efectos estimados</h2>
<div class="cell" data-warnings="false">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:60%; ">
<table class="lightable-paper lightable-hover caption-top" data-quarto-postprocess="true" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;border-bottom: 0;">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Primera etapa y forma reducida
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Primera etapa
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Forma reducida
</div></th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Variable dep.: fue apercibido
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Variable dep.: reincidencia
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(1)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(2)*</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(3)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(4)*</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Asignado a ser apercibido (\(T\))</td>
<td style="text-align: center;">0.786 (0.043)</td>
<td style="text-align: center;">0.733 (0.043)</td>
<td style="text-align: center;">0.114 (0.047)</td>
<td style="text-align: center;">0.108 (0.041)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arma</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.064 (0.045)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.004 (0.042)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Influencia químicos</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">-0.088 (0.040)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.052 (0.038)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Media variable dep.</td>
<td style="text-align: center;">0.567</td>
<td style="text-align: center;">0.567</td>
<td style="text-align: center;">0.178</td>
<td style="text-align: center;">0.178</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Nota:</span> <sup></sup> Tabla 2 en Angrist (2006). * Indica que se incluyen como variables de control indicadoras para año, trimestre, raza no blanca y raza mixta.</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>

</div>
<ul>
<li><p>Habíamos obtenido antes la columna (1), pero como una diferencia de medias: <span class="math inline">\(E(D_i|Z_i=1)-E(D_i|Z_i=0)=0.797-0.011=0.786\)</span></p></li>
<li><p>Mientras que también habíamos encontrado (3): <span class="math inline">\(E(y_i|Z_i=1)-E(y_i|Z_i=0)=0.211-0.097=0.0.114\)</span></p></li>
</ul>
</section>
<section id="efectos-estimados-2" class="slide level2">
<h2>Efectos estimados</h2>
<p><strong>Efecto del tratamiento</strong></p>
<ul>
<li><p>Noten que con nuestro estimador de MC2E obtenemos exactamente lo que antes habíamos calculado como <span class="math inline">\(\lambda_{LATE}=\frac{ITT_y}{ITT_D}=\frac{E(y_i|Z_i=1)-E(y_i|Z_i=0)}{E(D_i|Z_i=1)-E(D_i|Z_i=0)}=0.145\)</span></p></li>
<li><p>Vean que al estimar la ecuación estructural por MCO obtenemos un coeficiente cercano a 0.070</p></li>
<li><p>Más aún, sabemos que el coeficiente de MCO es inconsistente</p></li>
</ul>
</section>
<section id="efectos-estimados-3" class="slide level2">
<h2>Efectos estimados</h2>
<div class="cell" data-warnings="false">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:50%; ">
<table class="lightable-paper lightable-hover caption-top" data-quarto-postprocess="true" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;border-bottom: 0;">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Impactos de ser apercibido en la reincidencia (MCO y LATE)
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
MCO
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
VI/MC2E
</div></th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Variable dep.: reincidencia
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(1)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(2)*</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(3)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">(4)*</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Apercibido</td>
<td style="text-align: center;">0.087 (0.044)</td>
<td style="text-align: center;">0.070 (0.038)</td>
<td style="text-align: center;">0.145 (0.060)</td>
<td style="text-align: center;">0.140 (0.053)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arma</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.010 (0.043)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.005 (0.043)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Influencia químicos</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.057 (0.039)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.064 (0.039)</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Nota:</span> <sup></sup> Tabla 3 en Angrist (2006). * Indica que se incluyen como variables de control indicadoras para año, trimestre, raza no blanca y raza mixta.</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>

</div>
<ul>
<li><p>Usando el estimador de MC2E obtenemos exactamente lo que antes habíamos calculado como <span class="math inline">\(\lambda_{LATE}=\frac{ITT_y}{ITT_D}=\frac{E(y_i|Z_i=1)-E(y_i|Z_i=0)}{E(D_i|Z_i=1)-E(D_i|Z_i=0)}=0.145\)</span></p></li>
<li><p>Al estimar la ecuación estructural por MCO obtenemos un coeficiente cercano a 0.070</p></li>
<li><p>Pero sabemos que el coeficiente de MCO es inconsistente</p></li>
</ul>
</section>
<section id="late-es-igual-atet-en-este-caso" class="slide level2">
<h2>LATE es igual ATET en este caso</h2>
<ul>
<li>Noten que este estudio tiene lo que se conoce como <em>no cumplidores de un solo lado</em></li>
</ul>
<div class="cell" data-warnings="false">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:50%; ">
<table class="lightable-paper lightable-hover caption-top" data-quarto-postprocess="true" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;border-bottom: 0;">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Tipos de individuos
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">\(D_i(0)=0\)</td>
<td style="text-align: center;">\(D_i(0)=1\)</td>
</tr>
<tr class="even">
<td style="text-align: left;">\(D_i(1)=0\)</td>
<td style="text-align: center;">\(Y_i(1,0)-Y_i(0,0)=0\)</td>
<td style="text-align: center;">\(Y_i(1,0)-Y_i(0,1)=-(Y_i(1)-Y_i(0))\)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Nunca cumplidor</td>
<td style="text-align: center;">Retador</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">\(D_i(1)=1\)</td>
<td style="text-align: center;">\(Y_i(1,1)-Y_i(0,0)=Y_i(1)-Y_i(0)\)</td>
<td style="text-align: center;">\(Y_i(1,1)-Y_i(0,1)=0\)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Cumplidor</td>
<td style="text-align: center;">Siempre adoptador</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Nota:</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Adaptado de la tabla 1 en Angrist, Imbens &amp; Rubin (1996).</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>

</div>
<ul>
<li><p>Cuando la asignación es <strong>apercibir</strong>, en el 20.27% de los casos la acción fue arrestar y en el 79.73% efectivamente fue apercibir</p></li>
<li><p>En cambio, cuando se indica <strong>no apercibir</strong>, es decir, arrestar, la adopción es casi perfecto (salvo un caso)</p></li>
</ul>
<div class="fragment">
<ul>
<li>En otras palabras, en este caso no hay <strong>siempre cumplidores</strong></li>
<li>No hay individuos que hayan sido <em>apercibidos</em> independientemente de la asignación</li>
</ul>
</div>
</section>
<section id="late-es-igual-atet-en-este-caso-1" class="slide level2">
<h2>LATE es igual ATET en este caso</h2>
<ul>
<li>Recordemos que el grupo de quienes reciben el tratamiento está compuesto de los cumplidores y los siempre adoptadores</li>
<li>En este caso en particular: <span class="math display">\[\lambda_{LATE}=E(y_{1i}-y_{0i}|C_i=1)=E(y_{1i}-y_{0i}|D_i=1)=ATET\]</span></li>
</ul>
<div class="fragment">
<ul>
<li>Esto ocurre en los casos en que:
<ul>
<li>Algunos de los asignados al tratamiento, <span class="math inline">\(z_i=1\)</span> lo reciben mientras otros no</li>
<li>Nadie de los asignados al control, <span class="math inline">\(z_i=0\)</span> tiene acceso al tratamiento</li>
</ul></li>
</ul>
</div>
</section></section>
<section id="section" class="title-slide slide level1 inverse center middle">
<h1></h1>
<p>Material de clase en versión preliminar.</p>
<p><strong>No reproducir, no distribuir, no citar.</strong></p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/122010/logo_cide_verde.png?itok=NUstTkpt" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>