on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e '.libPaths("/opt/R/4.5.1/lib/R/library"); install.packages(c("rmarkdown", "knitr", "tidyverse", "stargazer", "janitor", "sandwich", "gt", "gtExtras"), repos="https://cloud.r-project.org")'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site with Quarto
        run: quarto render .

      - name: Publish to gh-pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
